### ISSUE TITLE
[BUG]: Timeshift (FFWD/Rewind) works for TV but not Radio

### ISSUE THREAD

**Issue by dkadioglu** [tvheadend/tvheadend#1604]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2190~g2151348f7

### Platform

Other..

### Architecture

ARMv8 (aarch64)

### Category

Timeshifting

### Description

This is a ticket, I have already opened three weeks ago in Redmine: http://tvheadend.org/issues/6319. I hope, it is ok to copy it over here.

I have the following issue: Timeshift (Pause/FF/Rewind) for TV works, for Radio not. This happens on a RPi4 on Arch Linux and HTS Tvheadend 4.3-2187~gfd8b9e8ba.

After having asked about this in the following locations...
https://tvheadend.org/boards/5/topics/43179
https://forum.libreelec.tv/thread/27773-pvr-hts-timeshift-for-radio
https://forum.kodi.tv/showthread.php?tid=375590

...the conclusion seems to be, that timeshift (including Pause/FF/Rewind) only works for TV and not for Radio.
ksooo, the developer of the Kodi addon pvr.hts, states: Tvheadend does not send any timeshift buffer information for radio channels via htsp. (https://forum.kodi.tv/showthread.php?tid=375590&pid=3177731#pid3177731)

As I wrote in the mentioned forum threads, I was not able to use timeshift for radio with any player. So I cannot test with anything else than Kodi and its addon pvr.hts.

Is this known? If yes, is there a reason? Can it be fixed?
If it is a bug, what information do you need?

Thanks and best

**Comment by Flole998** [comment]
Yes, opening issues here again is perfectly fine if they still exist.

I've just paused a radio channel on Kodi, and it's displaying "Timeshift" aswell as the amount of seconds it's shifted by. However, I can't jump forward by a certain amount of seconds like I can for TV. Not sure if that's Kodi or Tvheadends limitation though.

**Comment by ksooo** [comment]
> I've just paused a radio channel on Kodi, and it's displaying "Timeshift" aswell as the amount of seconds it's shifted by. 

That's just fake. 

> However, I can't jump forward by a certain amount of seconds like I can for TV.

That's exactly because tvheadend sends no timeshift data via HTSP for radio channels. That's definitely the case, since ever.

**Comment by Flole998** [comment]
I've had a brief look and Tvheadend keeps a record of iframes, which only exist in video-streams. Is that maybe the info that's sent to Kodi for video streams and is missing for audio streams?

**Comment by ksooo** [comment]
@Flole998 I can only tell from the perspective of a HTSP client, that for proper time shift support the HTSP server must provide data via "timeshiftStatus"

https://github.com/tvheadend/tvheadend/blob/master/src/htsp_server.c#L4533

but this does not happen for radio, but is working for tv.

**Comment by Flole998** [comment]
That's indeed because it is relying on iframes, which only exist for a video-stream. I have no idea how this should be handled for audio-only streams and how Tvheadend should be able to search within that stream.

**Comment by Flole998** [comment]
I might have an idea, but I have absolutely no idea if it will work or not. First we need to detect if it is an audio-only stream, then we use the current iframe list to store info about ALL audio frames (as audio has less bandwith than video there are less frames, so this should be fine), and then we hope that everything just works (I guess it won't as there are other changes needed aswell, but let's see).

**Comment by Flole998** [comment]
@dkadioglu @ksooo Could you please test this patch:

```
diff --git a/src/timeshift/private.h b/src/timeshift/private.h
index 5c6000e2a..16536229c 100644
--- a/src/timeshift/private.h
+++ b/src/timeshift/private.h
@@ -131,6 +131,7 @@ typedef struct timeshift {
   int                         file_segments; ///< Count of segments in files
 
   int                         vididx;     ///< Index of (current) video stream
+  int                         audidx;     ///< Index of (current) audio stream
 
   streaming_start_t          *smt_start;  ///< Streaming start info
 
diff --git a/src/timeshift/timeshift_writer.c b/src/timeshift/timeshift_writer.c
index 8eb22a167..40b963865 100644
--- a/src/timeshift/timeshift_writer.c
+++ b/src/timeshift/timeshift_writer.c
@@ -249,6 +249,13 @@ static void _update_smt_start ( timeshift_t *ts, streaming_start_t *ss )
       ts->vididx = ss->ss_components[i].es_index;
       break;
     }
+
+  /* Update audio index */
+  for (i = 0; i < ss->ss_num_components; i++)
+    if (SCT_ISAUDIO(ss->ss_components[i].es_type)) {
+      ts->audidx = ss->ss_components[i].es_index;
+      break;
+    }
 }
 
 /*
@@ -283,9 +290,9 @@ static inline ssize_t _process_msg0
     if (err > 0) {
       th_pkt_t *pkt = sm->sm_data;
 
-      /* Index video iframes */
-      if (pkt->pkt_componentindex == ts->vididx &&
-          pkt->v.pkt_frametype    == PKT_I_FRAME) {
+      /* Index video iframes or audio frames for audio-only streams*/
+      if ((pkt->pkt_componentindex == ts->vididx && pkt->v.pkt_frametype == PKT_I_FRAME) ||
+          (ts->vididx == -1 && pkt->pkt_componentindex == ts->audidx)) {
         timeshift_index_iframe_t *ti = calloc(1, sizeof(timeshift_index_iframe_t));
         memoryinfo_alloc(&timeshift_memoryinfo, sizeof(*ti));
         ti->pos  = tsf->size;

```

**Comment by ksooo** [comment]
> Could you please test this patch:

Sorry no. No tvh build env available currently.

**Comment by dkadioglu** [comment]
@ksooo Thank you very much for chiming in and indeed, you're right, pausing works for sure, only timeshifting is not working.
@Flole998 Thank you very much for your fast response, looking into this and proposing a fix! I just built TVHeadend with this patch and installed it. Now, if I pause in Kodi, the OSD says that it is timeshifting and the timeshift counter is counting upwards. And whenever I press play again, the audio starts, where I paused. I also can forward or rewind the stream, as it is the case with Live TV. So, after this first test, from my point of view, timeshift for radio works now.
@ksooo @Flole998 Is there anything further I should test, exept just playing, pausing and forwarding or rewinding the stream?

**Comment by Flole998** [comment]
Please check the memory usage in the Tvheadend web UI (I think in the debug tab) to make sure it's not excessive when time shifting audio. Also please check if timeshifting video and jumping in that timeshift still works (you can also compare the Webinterface memory stats for a minute of audio timeshift and a minute of video timeshift to get a "feeling" how those values should be).

**Comment by dkadioglu** [comment]
Following are screenshots from the web ui debug tab -> memory information (on demand timeshifting is disabled):
After ~1min. LiveTV just playing, without pausing or jumping:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/2fd6911d-12f4-4a0d-a7a4-0c710aad0aa8)
After ~1min. Radio just playing, without pausing or jumping:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/60d4f455-94b8-4253-8b22-418bc8d6e161)
After pausing for ~1min. and jumping a little bit around in Live TV:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/9b9e60f5-ac4e-4ece-a5f5-1f6bc6df91b5)
After pausing for ~1min. and jumping a little bit around in Radio:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/0da8aae9-887f-4191-b200-d231b090301a)

**Comment by Flole998** [comment]
That's too much memory usage. It needs to be fixed in some way, but I am not yet sure how. A simple counter might be enough though.

**Comment by Flole998** [comment]
I have added the change now, but it needs to be looked at again and improved.

**Comment by dkadioglu** [comment]
Thank you very much again for fixing this!
For the sake of completeness, I did the same tests again. In the following are screenshots from the web ui debug tab -> memory information (on demand timeshifting is disabled):
After ~1min. LiveTV just playing, without pausing or jumping:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/9a8a22ee-d762-4a68-8c84-e8a14f527aff)
After ~1min. Radio just playing, without pausing or jumping:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/20b844e5-da7d-4846-af51-96ccc768b576)
After pausing for ~1min. and jumping a little bit around in Live TV:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/79ac905e-0cec-4f6b-b04d-0357b0f82bbe)
After pausing for ~1min. and jumping a little bit around in Radio:
![image](https://github.com/tvheadend/tvheadend/assets/1633773/3d6de555-112a-448d-a411-9e612f018a55)

I hope, the numbers are better now. Timeshift still works as expected for Live TV and Radio. I am using HTS Tvheadend 4.3-2212~gac4a041e0, so yesterdays commit with the packet counter should be included.

**Comment by Flole998** [comment]
Yes I am happy with those now
