### ISSUE TITLE
[BUG]: Escaping of newline characters in Content-Disposition-Header when accessing recordings

### ISSUE THREAD

**Issue by mk-nwse** [tvheadend/tvheadend#1605]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2141~gc531383ca

### Platform

Other..

### Architecture

Intel x86_64

### Category

PVR/DVR

### Description

When a recorded TV show/movie contains newline characters, they are not being properly escaped int he Content-Disposition Header in the GET /dvrfile/<UUID> request.

This causes an invalid HTTP-Response to be produced. As not even cURL was happy with that response, I had to use telnet to see the issue:

```
> telnet 127.0.0.1 9981
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /dvrfile/fe01d979d6cc0c5458a109aeb54a76e2?ticket=0bf42a0620bb2309c8258d92c17d85c5c52a77a3 HTTP/1.1
Host: 127.0.0.1:9981
Accept: */*

HTTP/1.1 200 OK
Server: HTS/tvheadend
Last-Modified: Thu, 25 Jan 2024 13:13:00 GMT
Expires: Thu, 25 Jan 2024 13:13:10 GMT
Cache-Control: max-age=10
Connection: Keep-Alive
Content-Type: video/x-matroska
Content-Length: 141353673
Content-Disposition: attachment; filename="Detektiv Conan - - Kogoro, betrunken in Satsuma (1)
Animation, J 2004
Altersfreigabe: ab 12.mkv"; filename*=UTF-8''Detektiv%20Conan%20-%20-%20Kogoro%2C%20betrunken%20in%20Satsuma%20%281%29%0AAnimation%2C%20J%202004%0AAltersfreigabe%3A%20ab%2012.mkv

Eߣ�B��B�B�BB��matroskaB��B��S�l�M�t�M��S��I�fS���M��S��T�kS��fM��S��T�gS���M��S��S�kS�l�)�A�I�f�s���}+R;">�
```

As you see in the response, the Content-Disposition-Header contains newline characters. As they are not properly escaped, it causes `Animation, J 2004` to be in it's own line. As every header needs to contain a `:`, HAProxy as well as cURL refuse to handle that http response.

Expected: newline-characters are removed or replaced by maybe whitespaces before being inserted into HTTP-headers.

Interestingly, this does not always seem to happen, as I have another recording, where the Content-Disposition Header is valid:

```
> telnet 127.0.0.1 9981
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /dvrfile/6444bb0edc18cf7c2e2a57a67f71bc9f?ticket=5d9b69671f14d6783e099ff60adb04bf5b0a55f3 HTTP/1.1
Host: 127.0.0.1:9981
Accept: */*

HTTP/1.1 200 OK
Server: HTS/tvheadend
Last-Modified: Thu, 25 Jan 2024 13:21:10 GMT
Expires: Thu, 25 Jan 2024 13:21:20 GMT
Cache-Control: max-age=10
Connection: Keep-Alive
Content-Type: video/mp2t
Content-Length: 639456996
Content-Disposition: attachment; filename="Detektiv-Conan-----Kogoro,-betrunken-in-Satsuma-(1)_Animation,-J-2004_Altersfreigabe_-ab-12.ts"; filename*=UTF-8''Detektiv-Conan-----Kogoro%2C-betrunken-in-Satsuma-%281%29_Animation%2C-J-2004_Altersfreigabe_-ab-12.ts
```

Here it seems to be properly replaced.
The only two differences between them:

1) The broken recording was done using the Matroska profile, while the working one was the default "pass" profile
2) The broken recording comes from a TV-Channel that is configured to use existing EPG-Data from another channel (in fact: the working one). While the working recordings EPG-Data came from the cable provider itself.

EDIT:

I figured out, that this seem to relate to the `Remove all unsafe characters from filename:` setting in the recording profile.
Even though there is an easy way to work around it, I would still like to call this a bug, because no setting should ever produce invalid HTTP responses.

**Comment by Flole998** [comment]
Yeah, that should not happen, we need to clear linebreaks here: https://github.com/tvheadend/tvheadend/blob/7b762336e1a4f7cfdc154d394fb17b1a26659cf1/src/webui/webui.c#L2240
