### ISSUE TITLE
[BUG]: Backups including all recordings, bzip going mad, disk filling up (90+Gb per backup).

### ISSUE THREAD

**Issue by ledow** [tvheadend/tvheadend#1625]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3.2209 (and before)

### Platform

Ubuntu 22.04 (Jammy)

### Architecture

ARMv8 (aarch64)

### Category

Crashes

### Description

I installed tvheadend from the cloudsmith.io Ubuntu packages on a clean Ubuntu only a few weeks again - worked fine for the last few weeks.

Now my disk is full and I noticed a bzip2 process sucking up 100% CPU and it was a tvheadend backup process.

It appears to be configured to use a recordings folder in /var/lib/tvheadend/recordings, and this isn't excluded from backup and thus it's backing up EVERYTHING.

I haven't imported or changed location, this was the default I was given by the package.

From the files it seems like it's been doing it on 4.3.2192, 2193 and 2209 and possibly further back but I can't tell.

Now my tvHeadend is entirely unresponsive ("refuse to connect"), and I had to purge the backups folder to try to get enough space back to get the machine to work.

How do I stop these backups including that folder and / or change the recordings folder without access to the GUI?

### Reproduction

Installed cloudsmith.io Ubuntu package on a clean machine
Recorded programs.
Disk filled until the backups process just hung because of no disk space.

**Comment by Flole998** [comment]
This issue report is missing debug logs.

**Comment by mamarley** [comment]
This should be fixed by https://github.com/tvheadend/tvheadend/pull/1630.
