### ISSUE TITLE
Add ERRNO to Log Entries Regarding File System Errors

### ISSUE THREAD

**Issue by DeltaMikeCharlie** [tvheadend/tvheadend#1638]
### Description

Add the ERRNO to log messages regarding file system error.

Triggered by this forum post:
https://tvheadend.org/d/8520-change-default-folders-for-tv-recordings-and-timeshift-on-ubuntu-2204

https://github.com/tvheadend/tvheadend/blob/b91587037c6099e77d233877162e36138c62e5b2/src/dvr/dvr_rec.c#L127

```
  if(stat(de->de_config->dvr_storage, &st) || !S_ISDIR(st.st_mode)) {
    tvherror(LS_DVR, "the directory '%s' is not accessible", de->de_config->dvr_storage);
    ret = -EIO;
    goto _return;
  }
```

Adding the ERRNO plus the ERRNO description would have provided the user with more troubleshooting information.

### Help and Guidance

This is a placeholder following a discussion with @Flole998.

### Acceptance

- [X] The proposal will be developed and maintained by me

**Comment by DeltaMikeCharlie** [comment]
Note: The strerror_r() function is similar to strerror(), but is thread safe.

**Comment by Flole998** [comment]
strerror is used everywhere else, we should continue using it even though it could theoretically cause incorrect log messages when multiple error messages are printed at the exact same time and when the implementation uses a single, static buffer. Usually that is not an issue though.
