### ISSUE TITLE
[BUG]: Services with multiple streams

### ISSUE THREAD

**Issue by Chris230291** [tvheadend/tvheadend#1652]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2199~g7b762336e

### Platform

Other..

### Architecture

Intel x86_64

### Category

DVB

### Description

There are some packages where services contain multiple streams.
Here is an example package: https://flysat.com/en/package/abertis-dtt-17/hispasat-30w-6
Is it possible to support these types of services?

Thanks,
Chris

**Comment by Flole998** [comment]
Not a bug if it's not supported.

**Comment by Chris230291** [comment]
OK, sorry.
I see the transponders get detected, but the services do not.

![image](https://github.com/tvheadend/tvheadend/assets/5328818/0d23b265-cbc9-41eb-ab59-d37888db8f07)

![image](https://github.com/tvheadend/tvheadend/assets/5328818/00c7eaa4-6bd7-4cca-add4-13d3293db852)

**Comment by Chris230291** [comment]
I think you are right, and it just isn't supported.
There's another multistream standard that does work (the one where you specify pls “root”, “gold”, etc).
The type I linked to is becoming very popular across Europe.
It would be great if it could be supported.

**Comment by Flole998** [comment]
To be honest: I don't have a clue what you are trying to do there or what kind of standard you are talking about. Make a forum post with as many details as possible, I'm sure someone will try to help you there.

**Comment by Chris230291** [comment]
Sorry, I am forever getting spam from the forum, so I would rather not.
I believe it is DVB-T2 over DVB-S2.
https://dvb.org/wp-content/uploads/2019/12/a136_dvb-t2-modulator-interface.pdf
It was bought up by myself and others on the forum several years ago.
Today I noticed that the mux's that use this standard had services, so I thought I would revisit.
