### ISSUE TITLE
[BUG]: Docker images don't have "--enable-debugging"

### ISSUE THREAD

**Issue by lars18th** [tvheadend/tvheadend#1671]
### Tvheadend Version

v4.2 (unsupported)

### Build Number

4.3-2299~g79aaa1434

### Platform

Other..

### Architecture

Intel x86_64

### Category

Other..

### Description

With the current docker images it's imposible to debug anything. When you use something like `-e RUN_OPTS=" --stderr --trace httpc,upnp,udp,satip"` the debug is not enabled. So, I recommend to provide different container images with debug and release modes.

**Comment by Flole998** [comment]
Not a bug but rather a feature request. If you want to work on it please go ahead, otherwise I'll close this.

For debugging you can use the Webinterface, which will display debug logs and allows specifying a log file and various other settings.
