### ISSUE TITLE
[BUG]: "An unknown error occurred." when trying to play inline using TV icon on Firefox

### ISSUE THREAD

**Issue by RafaelLinux** [tvheadend/tvheadend#1672]
### Tvheadend Version

v4.2 (unsupported)

### Build Number

4.2.7-44

### Platform

Other..

### Architecture

ARMv7 (arm)

### Category

HTSP

### Description

Tvheadend 4.2.7-44 ~ LibreELEC Tvh-addon v9.0.118

Despite I know this version is unsupported, as I can't upgrade, I'll try to get an answer.

I have been using TVheadend for years, but I was forced to use remote clients for Android, as Firefox always shows the message "An unknown error occurred." when I try to play from the Firefox browser using the small TV icon. 
![imagen](https://github.com/tvheadend/tvheadend/assets/13048959/2985c34d-9b8a-4e74-81d7-9503b3876604)

Also, the Firefox debug console shows.

`Cannot play media. No decoders for requested formats: video/MP2T, video/webm; codecs="vp8.0 vorbis", application/x-mpegURL; codecs="avc1.42E01E mp4a.40 .2", application/vnd.apple.mpegURL; codecs="avc1.42E01E mp4a.40.2", video/MP2T; codecs="avc1.42E01E mp4a.40.2", video/x-matroska; codecs="avc1.42E01E mp4a.40 .2", video/MP2T, video/webm; codecs="vp8.0 vorbis", application/x-mpegURL; codecs="avc1.42E01E mp4a.40 .2", application/vnd.apple.mpegURL; codecs="avc1.42E01E mp4a.40.2", video/MP2T; codecs="avc1.42E01E mp4a.40.2", video/x-matroska; codecs="avc1.42E01E mp4a.40.2"`

However, I have found that browsers like Chrome, Chromium or MSEdge for Linux do allow to play the TV directly by clicking on the mentioned icon, being under the same configuration on the same computer. Any idea why the error is only shown in Firefox?

Thanks

**Comment by Flole998** [comment]
Not a bug, unsupported version, questions should go into the forum.

**Comment by RafaelLinux** [comment]
Ok, thanks
