### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by Lalarian** [tvheadend/tvheadend#1676]
-

**Comment by Flole998** [comment]
The lists are not maintained by us anymore. Please submit your request to the upstream repo at LinuxTV (https://git.linuxtv.org/dtv-scan-tables.git/).

**Comment by Lalarian** [comment]
Thanks.

**Comment by Flole998** [comment]
Where are the outdated files in this repo?

**Comment by Lalarian** [comment]
> Where are the outdated files in this repo?

Hello!

Sorry, I just noticed your question.
At least these files are outdated:
https://github.com/tvheadend/dtv-scan-tables/tree/tvheadend/dvb-c/de-Hessen-Unitymedia
https://github.com/tvheadend/dtv-scan-tables/tree/tvheadend/dvb-c/de-Unitymedia
https://github.com/tvheadend/dtv-scan-tables/tree/tvheadend/dvb-c/de-Kabel_Deutschland-Hannover
https://github.com/tvheadend/dtv-scan-tables/tree/tvheadend/dvb-c/de-Kabel_BW

**Comment by Flole998** [comment]
That is not part of this repo though. And that repo is deprecated, so even if you would submit a patchset, it wouldn't help at all. The proper process is to submit it to the LinuxTV repo.
