### ISSUE TITLE
[BUG]: No audio language/description

### ISSUE THREAD

**Issue by mnlipp** [tvheadend/tvheadend#1682]
### Tvheadend Version

v4.3 (development)

### Build Number

2315~gab6ea89b1

### Platform

Other..

### Architecture

Intel x86_64

### Category

IPTV

### Description

Using a typical german mux such as https://zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8, there are several audio streams. Both the "built-in" scan and the scan with A/V library (which is required to  get working audio) drop (or do not extract in the first place) the language and description for the audio channels (which is shown when using the URL in e.g. vlc). This makes using the audio streams impossible because in a front-end you just have a list of streams with numbers and don't know which one to choose.

### Reproduction

1. Configure the sample mux.
2. Have a look at the information for the created stream (or open vlc with the stream from tvheadend).

**Comment by Flole998** [comment]
HLS is not a supported input format. Provide a MPEG-TS input stream to Tvheadend.
