### ISSUE TITLE
Internal epg grabber modules dublicates in list

### ISSUE THREAD

**Issue by multijohn** [tvheadend/tvheadend#1698]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2323~g73a6bd00d

### Platform

Ubuntu 22.04 (Jammy)

### Architecture

Intel x86_64

### Category

WebGUI

### Description

Hello,
I am seeing dublicates for epg internal modules 
It reads normally from /usr/bin and from /bin which is a symlink of /usr/bin.
Why is that happening? Is something in my installation that i must fix, or it normal behaviour?
Thank you!!!!

**Comment by Flole998** [comment]
Questions should go into the forum.
