### ISSUE TITLE
[BUG]: Tvheadend firstrun /home/hts user creation fails on Debian LXC Proxmox container

### ISSUE THREAD

**Issue by walterav1984** [tvheadend/tvheadend#1699]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2323~g73a6bd00d

### Platform

Debian 12 Bookworm

### Architecture

x86_64

### Category

Packaging

### Description

Issue:
Installing tvheadend onto Debian12 bookworm LXC container inside a Proxmox 8.2.2 machine fails to create a `/home/hts` user&folder, although apt installation progress %87 shows that firstrun/user folder creation does happen...

```
Setting up tvheadend (4.3-2323~g73a6bd00d~bookworm) ...
Creating user: hts...
Created symlink /etc/systemd/system/multi-user.target.wants/tvheadend.service -> /lib/systemd/system/tvheadend.service.
```

But it didn't create the htsuser/folder therefor tvheadend keeps running as `root` user with `/var/lib/tvheadend` as a config folder. The original username and password created during setup of tvheadend are working as intended if you logon in tvheadend webinterface.

Workaround:
After manually creating a `/home/hts` user&folder and do some terminal foo, which I cannot exactly reproduce on a new empty LXC container (have a ~200 line bash history file) it did leave me with a working tvheadend setup (SATIP DVB-C and HDHomerun DVB-C network tuners). However not sure if the permissions are right on the folder `.hts` folder.

```
root@debugtvhe:/home# ls -la hts/
total 36
drwxr-xr-x 6 hts  video 4096 May 23 07:20 .
drwxr-xr-x 3 root root  4096 May 22 15:52 ..
-rw-r--r-- 1 hts  video  220 Apr 23  2023 .bash_logout
-rw-r--r-- 1 hts  video 3526 Apr 23  2023 .bashrc
drwx------ 3 hts  video 4096 May 22 15:53 .config
drwxr-xr-x 3 root root  4096 May 23 07:20 .hts
-rw-r--r-- 1 hts  video  807 Apr 23  2023 .profile
drwxrwxrwx 2 hts  video 4096 May 22 15:53 .xmltv
drwxr-xr-x 2 hts  hts   4096 May 23 07:20 recordings
root@debugtvhe:/home# ls -la hts/.hts
total 12
drwxr-xr-x 3 root root  4096 May 23 07:20 .
drwxr-xr-x 6 hts  video 4096 May 23 07:20 ..
drwxr-xr-x 8 hts  hts   4096 May 23 07:21 tvheadend
```

My guess is that the `deb` packaging requirements are not strict enough to handle a stripped down Debian LXC container install but am not sure what the exact steps package requirements would be to fix this aka --firstrun adduser/useradd video group... isssue?

Any hints where to start checking logs during install?

### Logfile

apt -f install tvheadend
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libalgorithm-c3-perl libarchive-zip-perl libauthen-sasl-perl libavahi-client3 libavahi-common-data libavahi-common3
  libb-hooks-endofscope-perl libb-hooks-op-check-perl libclass-c3-perl libclass-c3-xs-perl libclass-data-inheritable-perl
  libclass-inspector-perl libclass-method-modifiers-perl libclass-methodmaker-perl libclass-singleton-perl libclass-xsaccessor-perl
  libclone-perl libcommon-sense-perl libconvert-binhex-perl libdata-dump-perl libdata-optlist-perl libdate-manip-perl
  libdatetime-format-builder-perl libdatetime-format-iso8601-perl libdatetime-format-sqlite-perl libdatetime-format-strptime-perl
  libdatetime-locale-perl libdatetime-perl libdatetime-timezone-perl libdbd-sqlite3-perl libdbi-perl libdevel-callchecker-perl
  libdevel-caller-perl libdevel-lexalias-perl libdevel-stacktrace-perl libdigest-bubblebabble-perl libdigest-hmac-perl libdvbcsa1
  libdynaloader-functions-perl libemail-address-perl libemail-find-perl libemail-valid-perl libencode-locale-perl
  libeval-closure-perl libexception-class-perl libexporter-lite-perl libexporter-tiny-perl libfcgi-bin libfcgi-perl libfcgi0ldbl
  libfile-chdir-perl libfile-homedir-perl libfile-listing-perl libfile-sharedir-perl libfile-slurp-perl libfile-which-perl
  libfont-afm-perl libhtml-form-perl libhtml-format-perl libhtml-fromtext-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-tree-perl libhttp-cache-transparent-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl libhttp-message-perl
  libhttp-negotiate-perl libidn12 libio-html-perl libio-sessiondata-perl libio-socket-ssl-perl libio-stringy-perl libjson-perl
  libjson-xs-perl liblingua-preferred-perl liblist-moreutils-perl liblist-moreutils-xs-perl liblog-tracemessages-perl
  liblwp-mediatypes-perl liblwp-protocol-https-perl liblwp-useragent-determined-perl libmailtools-perl libmime-tools-perl
  libmodule-implementation-perl libmodule-runtime-perl libmro-compat-perl libnamespace-autoclean-perl libnamespace-clean-perl
  libnet-dns-perl libnet-dns-sec-perl libnet-domain-tld-perl libnet-http-perl libnet-libidn-perl libnet-libidn2-perl
  libnet-smtp-ssl-perl libnet-ssleay-perl libpackage-stash-perl libpackage-stash-xs-perl libpadwalker-perl libparams-classify-perl
  libparams-util-perl libparams-validate-perl libparams-validationcompiler-perl libpcre3 libperl4-corelibs-perl libperlio-gzip-perl
  libreadonly-perl libref-util-perl libref-util-xs-perl libregexp-common-perl libregexp-ipv6-perl librole-tiny-perl libsoap-lite-perl
  libspecio-perl libsub-exporter-perl libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl libsub-name-perl
  libsub-quote-perl libtask-weaken-perl libterm-progressbar-perl libterm-readkey-perl libtie-ixhash-perl libtimedate-perl
  libtry-tiny-perl libtypes-serialiser-perl libunicode-string-perl liburi-encode-perl liburi-escape-xs-perl liburi-perl liburiparser1
  libvariable-magic-perl libwww-perl libwww-robotrules-perl libxml-dom-perl libxml-libxml-perl libxml-libxslt-perl
  libxml-namespacesupport-perl libxml-parser-perl libxml-perl libxml-regexp-perl libxml-sax-base-perl libxml-sax-expat-perl
  libxml-sax-perl libxml-treepp-perl libxml-twig-perl libxml-writer-perl libxml-xpathengine-perl libxmlrpc-lite-perl libxmltv-perl
  libxslt1.1 libxstring-perl perl-openssl-defaults xmltv-util
Suggested packages:
  libgssapi-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl libcrypt-ssleay-perl libscalar-number-perl
  libapache2-mod-perl2 libmime-lite-perl libnet-jabber-perl libtest-fatal-perl libbusiness-isbn-perl libauthen-ntlm-perl
  libxml-sax-expatxs-perl libunicode-map8-perl xml-twig-tools xmltv-gui debhelper libcgi-pm-perl liblinux-dvb-perl
Recommended packages:
  python python-requests
The following NEW packages will be installed:
  libalgorithm-c3-perl libarchive-zip-perl libauthen-sasl-perl libavahi-client3 libavahi-common-data libavahi-common3
  libb-hooks-endofscope-perl libb-hooks-op-check-perl libclass-c3-perl libclass-c3-xs-perl libclass-data-inheritable-perl
  libclass-inspector-perl libclass-method-modifiers-perl libclass-methodmaker-perl libclass-singleton-perl libclass-xsaccessor-perl
  libclone-perl libcommon-sense-perl libconvert-binhex-perl libdata-dump-perl libdata-optlist-perl libdate-manip-perl
  libdatetime-format-builder-perl libdatetime-format-iso8601-perl libdatetime-format-sqlite-perl libdatetime-format-strptime-perl
  libdatetime-locale-perl libdatetime-perl libdatetime-timezone-perl libdbd-sqlite3-perl libdbi-perl libdevel-callchecker-perl
  libdevel-caller-perl libdevel-lexalias-perl libdevel-stacktrace-perl libdigest-bubblebabble-perl libdigest-hmac-perl libdvbcsa1
  libdynaloader-functions-perl libemail-address-perl libemail-find-perl libemail-valid-perl libencode-locale-perl
  libeval-closure-perl libexception-class-perl libexporter-lite-perl libexporter-tiny-perl libfcgi-bin libfcgi-perl libfcgi0ldbl
  libfile-chdir-perl libfile-homedir-perl libfile-listing-perl libfile-sharedir-perl libfile-slurp-perl libfile-which-perl
  libfont-afm-perl libhtml-form-perl libhtml-format-perl libhtml-fromtext-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-tree-perl libhttp-cache-transparent-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl libhttp-message-perl
  libhttp-negotiate-perl libidn12 libio-html-perl libio-sessiondata-perl libio-socket-ssl-perl libio-stringy-perl libjson-perl
  libjson-xs-perl liblingua-preferred-perl liblist-moreutils-perl liblist-moreutils-xs-perl liblog-tracemessages-perl
  liblwp-mediatypes-perl liblwp-protocol-https-perl liblwp-useragent-determined-perl libmailtools-perl libmime-tools-perl
  libmodule-implementation-perl libmodule-runtime-perl libmro-compat-perl libnamespace-autoclean-perl libnamespace-clean-perl
  libnet-dns-perl libnet-dns-sec-perl libnet-domain-tld-perl libnet-http-perl libnet-libidn-perl libnet-libidn2-perl
  libnet-smtp-ssl-perl libnet-ssleay-perl libpackage-stash-perl libpackage-stash-xs-perl libpadwalker-perl libparams-classify-perl
  libparams-util-perl libparams-validate-perl libparams-validationcompiler-perl libpcre3 libperl4-corelibs-perl libperlio-gzip-perl
  libreadonly-perl libref-util-perl libref-util-xs-perl libregexp-common-perl libregexp-ipv6-perl librole-tiny-perl libsoap-lite-perl
  libspecio-perl libsub-exporter-perl libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl libsub-name-perl
  libsub-quote-perl libtask-weaken-perl libterm-progressbar-perl libterm-readkey-perl libtie-ixhash-perl libtimedate-perl
  libtry-tiny-perl libtypes-serialiser-perl libunicode-string-perl liburi-encode-perl liburi-escape-xs-perl liburi-perl liburiparser1
  libvariable-magic-perl libwww-perl libwww-robotrules-perl libxml-dom-perl libxml-libxml-perl libxml-libxslt-perl
  libxml-namespacesupport-perl libxml-parser-perl libxml-perl libxml-regexp-perl libxml-sax-base-perl libxml-sax-expat-perl
  libxml-sax-perl libxml-treepp-perl libxml-twig-perl libxml-writer-perl libxml-xpathengine-perl libxmlrpc-lite-perl libxmltv-perl
  libxslt1.1 libxstring-perl perl-openssl-defaults tvheadend xmltv-util
0 upgraded, 158 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.9 MB of archives.
After this operation, 130 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian bookworm/main amd64 libalgorithm-c3-perl all 0.11-2 [10.8 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 libarchive-zip-perl all 1.68-1 [104 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 libauthen-sasl-perl all 2.1600-3 [43.9 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 libavahi-common-data amd64 0.8-10 [107 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 libavahi-common3 amd64 0.8-10 [41.6 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 libavahi-client3 amd64 0.8-10 [45.5 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 libb-hooks-op-check-perl amd64 0.22-2+b1 [10.5 kB]
Get:8 http://deb.debian.org/debian bookworm/main amd64 libdynaloader-functions-perl all 0.003-3 [12.7 kB]
Get:9 http://deb.debian.org/debian bookworm/main amd64 libdevel-callchecker-perl amd64 0.008-2 [15.8 kB]
Get:10 http://deb.debian.org/debian bookworm/main amd64 libparams-classify-perl amd64 0.015-2+b1 [23.1 kB]
Get:11 http://deb.debian.org/debian bookworm/main amd64 libmodule-runtime-perl all 0.016-2 [19.6 kB]
Get:12 http://deb.debian.org/debian bookworm/main amd64 libtry-tiny-perl all 0.31-2 [22.6 kB]    
Get:13 http://deb.debian.org/debian bookworm/main amd64 libmodule-implementation-perl all 0.09-2 [12.6 kB]
Get:14 http://deb.debian.org/debian bookworm/main amd64 libsub-exporter-progressive-perl all 0.001013-3 [7496 B]
Get:15 http://deb.debian.org/debian bookworm/main amd64 libvariable-magic-perl amd64 0.63-1+b1 [44.0 kB]
Get:16 http://deb.debian.org/debian bookworm/main amd64 libb-hooks-endofscope-perl all 0.26-1 [19.6 kB]
Get:17 http://deb.debian.org/debian bookworm/main amd64 libclass-c3-perl all 0.35-2 [21.0 kB]         
Get:18 http://deb.debian.org/debian bookworm/main amd64 libclass-c3-xs-perl amd64 0.15-1+b3 [17.0 kB] 
Get:19 http://deb.debian.org/debian bookworm/main amd64 libclass-data-inheritable-perl all 0.08-3 [8588 B]
Get:20 http://deb.debian.org/debian bookworm/main amd64 libclass-inspector-perl all 1.36-3 [17.5 kB]    
Get:21 http://deb.debian.org/debian bookworm/main amd64 libclass-method-modifiers-perl all 2.14-1 [18.1 kB]
Get:22 http://deb.debian.org/debian bookworm/main amd64 libclass-methodmaker-perl amd64 2.24-2+b3 [184 kB]
Get:23 http://deb.debian.org/debian bookworm/main amd64 libclass-singleton-perl all 1.6-2 [12.5 kB]
Get:24 http://deb.debian.org/debian bookworm/main amd64 libclass-xsaccessor-perl amd64 1.19-4+b1 [36.4 kB]
Get:25 http://deb.debian.org/debian bookworm/main amd64 libclone-perl amd64 0.46-1 [13.7 kB]        
Get:26 http://deb.debian.org/debian bookworm/main amd64 libcommon-sense-perl amd64 3.75-3 [23.0 kB] 
Get:27 http://deb.debian.org/debian bookworm/main amd64 libconvert-binhex-perl all 1.125-3 [27.4 kB]
Get:28 http://deb.debian.org/debian bookworm/main amd64 libdata-dump-perl all 1.25-1 [28.4 kB]  
Get:29 http://deb.debian.org/debian bookworm/main amd64 libparams-util-perl amd64 1.102-2+b1 [24.8 kB]
Get:30 http://deb.debian.org/debian bookworm/main amd64 libsub-install-perl all 0.929-1 [10.5 kB]
Get:31 http://deb.debian.org/debian bookworm/main amd64 libdata-optlist-perl all 0.113-1 [10.6 kB]
Get:32 http://deb.debian.org/debian bookworm/main amd64 libdate-manip-perl all 6.91-1 [912 kB] 
Get:33 http://deb.debian.org/debian bookworm/main amd64 libfile-sharedir-perl all 1.118-3 [16.0 kB]
Get:34 http://deb.debian.org/debian bookworm/main amd64 libpackage-stash-perl all 0.40-1 [22.0 kB]
Get:35 http://deb.debian.org/debian bookworm/main amd64 libsub-identify-perl amd64 0.14-3 [10.9 kB]
Get:36 http://deb.debian.org/debian bookworm/main amd64 libsub-name-perl amd64 0.26-2+b1 [12.6 kB]
Get:37 http://deb.debian.org/debian bookworm/main amd64 libnamespace-clean-perl all 0.27-2 [17.8 kB]
Get:38 http://deb.debian.org/debian bookworm/main amd64 libnamespace-autoclean-perl all 0.29-2 [13.5 kB]
Get:39 http://deb.debian.org/debian bookworm/main amd64 libsub-exporter-perl all 0.989-1 [50.5 kB]
Get:40 http://deb.debian.org/debian bookworm/main amd64 libeval-closure-perl all 0.14-3 [11.2 kB]
Get:41 http://deb.debian.org/debian bookworm/main amd64 libdevel-stacktrace-perl all 2.0400-2 [26.8 kB]
Get:42 http://deb.debian.org/debian bookworm/main amd64 libexception-class-perl all 1.45-1 [34.6 kB]
Get:43 http://deb.debian.org/debian bookworm/main amd64 libparams-validationcompiler-perl all 0.31-1 [30.9 kB]
Get:44 http://deb.debian.org/debian bookworm/main amd64 libmro-compat-perl all 0.15-2 [11.8 kB]
Get:45 http://deb.debian.org/debian bookworm/main amd64 librole-tiny-perl all 2.002004-1 [21.4 kB]
Get:46 http://deb.debian.org/debian bookworm/main amd64 libsub-quote-perl all 2.006008-1 [21.8 kB]
Get:47 http://deb.debian.org/debian bookworm/main amd64 libxstring-perl amd64 0.005-2+b1 [8320 B]
Get:48 http://deb.debian.org/debian bookworm/main amd64 libspecio-perl all 0.48-1 [142 kB]
Get:49 http://deb.debian.org/debian bookworm/main amd64 libdatetime-locale-perl all 1:1.37-1 [2776 kB]
Get:50 http://deb.debian.org/debian bookworm/main amd64 libdatetime-timezone-perl all 1:2.60-1+2024a [265 kB]
Get:51 http://deb.debian.org/debian bookworm/main amd64 libdatetime-perl amd64 2:1.59-1 [116 kB]
Get:52 http://deb.debian.org/debian bookworm/main amd64 libdatetime-format-strptime-perl all 1.7900-1 [37.3 kB]
Get:53 http://deb.debian.org/debian bookworm/main amd64 libparams-validate-perl amd64 1.31-1 [64.4 kB]
Get:54 http://deb.debian.org/debian bookworm/main amd64 libdatetime-format-builder-perl all 0.8300-1 [63.8 kB]
Get:55 http://deb.debian.org/debian bookworm/main amd64 libdatetime-format-iso8601-perl all 0.16-2 [22.4 kB]
Get:56 http://deb.debian.org/debian bookworm/main amd64 libdatetime-format-sqlite-perl all 0.11-3 [7824 B]
Get:57 http://deb.debian.org/debian bookworm/main amd64 libdbi-perl amd64 1.643-4 [773 kB]
Get:58 http://deb.debian.org/debian bookworm/main amd64 libdbd-sqlite3-perl amd64 1.72-1 [179 kB]
Get:59 http://deb.debian.org/debian bookworm/main amd64 libpadwalker-perl amd64 2.5-1+b3 [18.3 kB]
Get:60 http://deb.debian.org/debian bookworm/main amd64 libdevel-caller-perl amd64 2.06-3+b1 [10.9 kB]
Get:61 http://deb.debian.org/debian bookworm/main amd64 libdevel-lexalias-perl amd64 0.05-3+b1 [8316 B]
Get:62 http://deb.debian.org/debian bookworm/main amd64 libdigest-bubblebabble-perl all 0.02-2.1 [7472 B]
Get:63 http://deb.debian.org/debian bookworm/main amd64 libdigest-hmac-perl all 1.04+dfsg-2 [9316 B]
Get:64 http://deb.debian.org/debian bookworm/main amd64 libdvbcsa1 amd64 1.1.0-4 [23.1 kB]
Get:65 http://deb.debian.org/debian bookworm/main amd64 libemail-address-perl all 1.913-1 [28.4 kB]
Get:66 http://deb.debian.org/debian bookworm/main amd64 perl-openssl-defaults amd64 7+b1 [7924 B]
Get:67 http://deb.debian.org/debian bookworm/main amd64 libnet-ssleay-perl amd64 1.92-2+b1 [317 kB]
Get:68 http://deb.debian.org/debian bookworm/main amd64 libio-socket-ssl-perl all 2.081-2 [219 kB]
Get:69 http://deb.debian.org/debian bookworm/main amd64 libnet-smtp-ssl-perl all 1.04-2 [6548 B]
Get:70 http://deb.debian.org/debian bookworm/main amd64 libtimedate-perl all 2.3300-2 [39.3 kB]
Get:71 http://deb.debian.org/debian bookworm/main amd64 libmailtools-perl all 2.21-2 [95.6 kB]
Get:72 http://deb.debian.org/debian bookworm/main amd64 libnet-dns-perl all 1.36-1 [377 kB]
Get:73 https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian bookworm/main amd64 tvheadend amd64 4.3-2323~g73a6bd00d~bookworm [15.9 MB]
Get:74 http://deb.debian.org/debian bookworm/main amd64 libnet-domain-tld-perl all 1.75-3 [31.9 kB]
Get:75 http://deb.debian.org/debian bookworm/main amd64 libemail-valid-perl all 1.203-1 [23.9 kB]
Get:76 http://deb.debian.org/debian bookworm/main amd64 libemail-find-perl all 0.10-dfsg-4 [13.4 kB]
Get:77 http://deb.debian.org/debian bookworm/main amd64 libencode-locale-perl all 1.05-3 [12.9 kB]
Get:78 http://deb.debian.org/debian bookworm/main amd64 libexporter-lite-perl all 0.09-2 [10.7 kB]
Get:79 http://deb.debian.org/debian bookworm/main amd64 libexporter-tiny-perl all 1.006000-1 [38.6 kB]
Get:80 http://deb.debian.org/debian bookworm/main amd64 libfcgi0ldbl amd64 2.4.2-2 [26.1 kB]
Get:81 http://deb.debian.org/debian bookworm/main amd64 libfcgi-bin amd64 2.4.2-2 [12.9 kB]
Get:82 http://deb.debian.org/debian bookworm/main amd64 libfcgi-perl amd64 0.82+ds-2 [25.2 kB]
Get:83 http://deb.debian.org/debian bookworm/main amd64 libfile-chdir-perl all 0.1008-1.1 [12.2 kB]
Get:84 http://deb.debian.org/debian bookworm/main amd64 libfile-which-perl all 1.27-2 [15.1 kB]
Get:85 http://deb.debian.org/debian bookworm/main amd64 libfile-homedir-perl all 1.006-2 [42.4 kB]
Get:86 http://deb.debian.org/debian bookworm/main amd64 libhttp-date-perl all 6.05-2 [10.5 kB]
Get:87 http://deb.debian.org/debian bookworm/main amd64 libfile-listing-perl all 6.15-1 [12.6 kB]
Get:88 http://deb.debian.org/debian bookworm/main amd64 libfile-slurp-perl all 9999.32-2 [26.7 kB]
Get:89 http://deb.debian.org/debian bookworm/main amd64 libfont-afm-perl all 1.20-4 [13.1 kB]
Get:90 http://deb.debian.org/debian bookworm/main amd64 libhtml-tagset-perl all 3.20-6 [11.7 kB]
Get:91 http://deb.debian.org/debian bookworm/main amd64 libregexp-ipv6-perl all 0.03-3 [5212 B]
Get:92 http://deb.debian.org/debian bookworm/main amd64 liburi-perl all 5.17-1 [90.4 kB]
Get:93 http://deb.debian.org/debian bookworm/main amd64 libhtml-parser-perl amd64 3.81-1 [101 kB]
Get:94 http://deb.debian.org/debian bookworm/main amd64 libio-html-perl all 1.004-3 [16.2 kB]
Get:95 http://deb.debian.org/debian bookworm/main amd64 liblwp-mediatypes-perl all 6.04-2 [20.2 kB]
Get:96 http://deb.debian.org/debian bookworm/main amd64 libhttp-message-perl all 6.44-1 [81.7 kB]
Get:97 http://deb.debian.org/debian bookworm/main amd64 libhtml-form-perl all 6.11-1 [33.1 kB]
Get:98 http://deb.debian.org/debian bookworm/main amd64 libhtml-tree-perl all 5.07-3 [211 kB]
Get:99 http://deb.debian.org/debian bookworm/main amd64 libhtml-format-perl all 2.16-2 [38.8 kB]
Get:100 http://deb.debian.org/debian bookworm/main amd64 libregexp-common-perl all 2017060201-3 [175 kB]
Get:101 http://deb.debian.org/debian bookworm/main amd64 libhtml-fromtext-perl all 2.07-3 [15.6 kB]
Get:102 http://deb.debian.org/debian bookworm/main amd64 libhttp-cookies-perl all 6.10-1 [19.6 kB]
Get:103 http://deb.debian.org/debian bookworm/main amd64 libhttp-negotiate-perl all 6.01-2 [13.1 kB]
Get:104 http://deb.debian.org/debian bookworm/main amd64 libnet-http-perl all 6.22-1 [25.3 kB]
Get:105 http://deb.debian.org/debian bookworm/main amd64 liblwp-protocol-https-perl all 6.10-1 [12.2 kB]
Get:106 http://deb.debian.org/debian bookworm/main amd64 libwww-robotrules-perl all 6.02-1 [12.9 kB]
Get:107 http://deb.debian.org/debian bookworm/main amd64 libwww-perl all 6.68-1 [186 kB]
Get:108 http://deb.debian.org/debian bookworm/main amd64 libhttp-cache-transparent-perl all 1.4-2 [14.6 kB]
Get:109 http://deb.debian.org/debian bookworm/main amd64 libhttp-daemon-perl all 6.16-1 [23.5 kB]
Get:110 http://deb.debian.org/debian bookworm/main amd64 libidn12 amd64 1.41-1 [83.8 kB]
Get:111 http://deb.debian.org/debian bookworm/main amd64 libio-sessiondata-perl all 1.03-3 [6316 B]
Get:112 http://deb.debian.org/debian bookworm/main amd64 libio-stringy-perl all 2.111-3 [56.5 kB]
Get:113 http://deb.debian.org/debian bookworm/main amd64 libjson-perl all 4.10000-1 [87.5 kB]
Get:114 http://deb.debian.org/debian bookworm/main amd64 libtypes-serialiser-perl all 1.01-1 [12.2 kB]
Get:115 http://deb.debian.org/debian bookworm/main amd64 libjson-xs-perl amd64 4.030-2+b1 [92.1 kB]
Get:116 http://deb.debian.org/debian bookworm/main amd64 liblog-tracemessages-perl all 1.4-6 [10.1 kB]
Get:117 http://deb.debian.org/debian bookworm/main amd64 liblingua-preferred-perl all 0.2.4-5 [11.1 kB]
Get:118 http://deb.debian.org/debian bookworm/main amd64 liblist-moreutils-xs-perl amd64 0.430-3+b1 [42.1 kB]
Get:119 http://deb.debian.org/debian bookworm/main amd64 liblist-moreutils-perl all 0.430-2 [46.9 kB]
Get:120 http://deb.debian.org/debian bookworm/main amd64 liblwp-useragent-determined-perl all 1.07-3 [9080 B]
Get:121 http://deb.debian.org/debian bookworm/main amd64 libmime-tools-perl all 5.510-1 [213 kB]
Get:122 http://deb.debian.org/debian bookworm/main amd64 libnet-dns-sec-perl amd64 1.20-1+b1 [49.1 kB]
Get:123 http://deb.debian.org/debian bookworm/main amd64 libnet-libidn-perl amd64 0.12.ds-4+b1 [17.1 kB]
Get:124 http://deb.debian.org/debian bookworm/main amd64 libnet-libidn2-perl amd64 1.01-2+b1 [16.4 kB]
Get:125 http://deb.debian.org/debian bookworm/main amd64 libpackage-stash-xs-perl amd64 0.30-1+b1 [19.8 kB]
Get:126 http://deb.debian.org/debian bookworm/main amd64 libpcre3 amd64 2:8.39-15 [341 kB]
Get:127 http://deb.debian.org/debian bookworm/main amd64 libperl4-corelibs-perl all 0.004-3 [38.5 kB]
Get:128 http://deb.debian.org/debian bookworm/main amd64 libperlio-gzip-perl amd64 0.20-1+b1 [17.3 kB]
Get:129 http://deb.debian.org/debian bookworm/main amd64 libreadonly-perl all 2.050-3 [23.1 kB]
Get:130 http://deb.debian.org/debian bookworm/main amd64 libref-util-perl all 0.204-2 [17.4 kB]
Get:131 http://deb.debian.org/debian bookworm/main amd64 libref-util-xs-perl amd64 0.117-2+b1 [14.1 kB]
Get:132 http://deb.debian.org/debian bookworm/main amd64 libtask-weaken-perl all 1.06-2 [9364 B]
Get:133 http://deb.debian.org/debian bookworm/main amd64 libxml-parser-perl amd64 2.46-4 [201 kB]
Get:134 http://deb.debian.org/debian bookworm/main amd64 libsoap-lite-perl all 1.27-3 [239 kB]
Get:135 http://deb.debian.org/debian bookworm/main amd64 libterm-readkey-perl amd64 2.38-2+b1 [24.5 kB]
Get:136 http://deb.debian.org/debian bookworm/main amd64 libterm-progressbar-perl all 2.23-1 [24.5 kB]
Get:137 http://deb.debian.org/debian bookworm/main amd64 libtie-ixhash-perl all 1.23-4 [11.7 kB]
Get:138 http://deb.debian.org/debian bookworm/main amd64 libunicode-string-perl amd64 2.10-2+b1 [97.1 kB]
#truncated log
#setup tvheadend username/password
#finishes after installing all packages etc

root@debugtvhe:/home# ps -e
    PID TTY          TIME CMD
      1 ?        00:00:06 systemd
     54 ?        00:00:00 systemd-journal
     92 ?        00:00:00 dhclient
     93 ?        00:00:00 cron
     94 ?        00:00:00 dbus-daemon
     99 ?        00:00:00 systemd-logind
    107 ?        00:00:00 systemd-network
    157 pts/0    00:00:00 agetty
    158 pts/1    00:00:00 login
    162 pts/2    00:00:00 agetty
    163 ?        00:00:00 sshd
    297 ?        00:00:00 master
    306 pts/1    00:00:00 bash
   2500 ?        00:00:00 tvheadend
   2723 ?        00:00:00 pickup
   2724 ?        00:00:00 qmgr
   2729 pts/1    00:00:00 ps

root@debugtvhe:/home# ls #no hts folder created

root@debugtvhe:/home# ls -la /var/lib/tvheadend/
total 52
drwxr-xr-x 10 hts  hts   4096 May 23 07:41 .
drwxr-xr-x 20 root root  4096 May 23 07:41 ..
-rw-r--r--  1 hts  video   11 May 23 07:41 .lock
drwxrwxrwx  2 hts  video 4096 May 23 07:41 .xmltv
drwx------  2 hts  video 4096 May 23 07:41 bouquet
drwx------  2 hts  video 4096 May 23 07:41 caclient
drwx------  2 hts  video 4096 May 23 07:41 codec
-rw-------  1 hts  video 1718 May 23 07:41 config
drwx------  3 hts  video 4096 May 23 07:41 dvr
drwx------  4 hts  video 4096 May 23 07:41 input
drwx------  2 hts  video 4096 May 23 07:41 profile
drwxr-xr-x  2 hts  hts   4096 May 23 07:41 recordings
-rw-------  1 hts  hts     55 May 23 07:41 superuser

root@debugtvhe:/home# systemctl status tvheadend
* tvheadend.service - Tvheadend - a TV streaming server and DVR
     Loaded: loaded (/lib/systemd/system/tvheadend.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-05-23 07:41:05 UTC; 12min ago
   Main PID: 2500 (tvheadend)
      Tasks: 44 (limit: 9140)
     Memory: 8.0M
        CPU: 14.499s
     CGroup: /system.slice/tvheadend.service
             `-2500 /usr/bin/tvheadend -f -p /run/tvheadend.pid -u hts -g video

May 23 07:41:23 debugtvhe tvheadend[2500]: tvhdhomerun: Found HDHomerun device 1220a78e with 2 tuners
May 23 07:41:23 debugtvhe tvheadend[2500]: tvhdhomerun: Using Network type : DVB-T
May 23 07:41:23 debugtvhe tvheadend[2500]: tvhdhomerun: Created frontend 1220A78E tuner 0
May 23 07:41:23 debugtvhe tvheadend[2500]: tvhdhomerun: Created frontend 1220A78E tuner 1
May 23 07:41:23 debugtvhe tvheadend[2500]: scanfile: DVB-S - loaded 1 regions with 116 networks
May 23 07:41:23 debugtvhe tvheadend[2500]: scanfile: DVB-T - loaded 46 regions with 1134 networks
May 23 07:41:23 debugtvhe tvheadend[2500]: scanfile: DVB-C - loaded 20 regions with 82 networks
May 23 07:41:23 debugtvhe tvheadend[2500]: scanfile: ATSC-T - loaded 2 regions with 13 networks
May 23 07:41:23 debugtvhe tvheadend[2500]: scanfile: ATSC-C - loaded 1 regions with 5 networks
May 23 07:41:23 debugtvhe tvheadend[2500]: scanfile: ISDB-T - loaded 2 regions with 1297 networks

### Reproduction

Install a host machine with ProxMox 8.2.2, create a new LXC container with the default CT-template `debian-12-standard_12.2-1_amd64.tar.zst` from the repository use a bridged networking interface. Open a console to that LXC, logon as root and continue to install tvheadend.

Altered the install instructions from the tvheadend website, taken into account that a stripped down Debian 12 bookworm LXC Proxmox container doesn't come with "sudo/curl" and only root user the following instructions were used:

```
apt update
apt install curl
apt upgrade #rebooted lxc after this
curl -1sLf 'https://dl.cloudsmith.io/public/tvheadend/tvheadend/setup.deb.sh' | bash
apt -f install tvheadend #-f install to fullfill dependencies 
```
The install will finish and you can logon into webinterface using the username/password setup earlier but all is running as `root` with config in `/var/lib/tvheadend` vs `hts:video` `/home/hts/.hts`.

**Comment by Flole998** [comment]
That is intended behavior, the legacy configuration directory is no longer created and used on new installations.

**Comment by walterav1984** [comment]
Thanks for quick reply, tvheadend itself is indeed working fine for a week on this container but I didn't new `/var/lib/tvheadend` was the new default...
