### ISSUE TITLE
[BUG]: CORS origin is not validated and only "blanked" on reload if the value is invalid

### ISSUE THREAD

**Issue by cmrtdev** [tvheadend/tvheadend#1700]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2323~g73a6bd00d

### Platform

Debian 12 (Bookworm)

### Architecture

Intel x86_64

### Category

Configuration

### Description

Note: credit for figuring this out goes to DeltaMikeCharlie in https://tvheadend.org/d/8630-cors-error

The description of CORS origin says

> Enter a domain (or IP) to allow cross-domain requests

when adding a bare domain (`example.com`) or IP upon Save the page reloads and the textbox is returned blank.

If the domain is added with the `http://` or `https://` prefix the Save operation is successful.

There are two issues:
1. the documentation should mention that the http:// or https:// prefixes are required
2. upon saving (or attempting to save) an invalid value (i.e. the bare domain or IP) the UI should show an error message or somehow display that the value entered was not accepted.

And #2 is optional (or could be postponed to another release) as long as the hover reflects that the prefix is needed.

### Reproduction

1. Configuration > General > Base
2. Add a domain without the http:// or https:// prefix to "CORS origin"
3. Save

The page reloads without saving the entry, but gives no indication of it.

**Comment by Flole998** [comment]
Documentation is part of another repository, and issue reports are not accepted for it. Instead, just go ahead and update the documentation yourself, that is faster anyways than trying to get someone else to add/fix it.

There is no error returned on validation in Tvheadend currently. That would be a new feature though. If you want to work on it let me know, then we can reopen this and track it as feature.

**Comment by cmrtdev** [comment]
@Flole998 ack on the error returned on validation; I'm afraid my C level is "no" so I couldn't work on backend validation. Frontend validation maybe, but not right now.

The documentation I understand is in another doc but I was specifically referring to the hovertext that, IIUC, is in [this `pot` file](https://github.com/tvheadend/tvheadend/blob/73a6bd00d29421da04be5e1c41b2097fdc9c148b/intl/tvheadend.pot#L3873).

I can update default (`en`) and `it`, should I just Google Translate the rest?

**Comment by cmrtdev** [comment]
Scratch half of that: should I update the `pot` file and then use Transifex for `it` (and then hopefully we get the other languages at some point?)

**Comment by Flole998** [comment]
The pot files should never be manually touched. Those files are all automatically generated. Update the c-code file instead, the location is shown in the pot file. Everything else works using transifex as you've already figured out.
