### ISSUE TITLE
[BUG]: tvheadend does not compile with ffmpeg7

### ISSUE THREAD

**Issue by EricV** [tvheadend/tvheadend#1715]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3~2336.g366e56290

### Platform

Other..

### Architecture

Intel x86_64

### Category

General

### Description

After fixing configure and Makefile to not use ffmpeg-6 components, it fails to compile because of incompatible API change due to  "channels layout" API change.

c->channels 

should be 

c->codecpar->ch_layout.nb_channels

### Logfile

src/muxer/muxer_libav.c: In function ‘lav_muxer_add_stream’:
src/muxer/muxer_libav.c:149:6: error: ‘AVCodecContext’ has no member named ‘channels’
  149 |     c->channels      = ssc->es_channels;
      |      ^~
src/muxer/muxer_libav.c: In function ‘lav_muxer_open_stream’:
src/muxer/muxer_libav.c:483:27: error: passing argument 6 of ‘avio_alloc_context’ from incompatible pointer type [-Wincompatible-pointer-types]
  483 |                           lav_muxer_write, NULL);
      |                           ^~~~~~~~~~~~~~~
      |                           |
      |                           int (*)(void *, uint8_t *, int) {aka int (*)(void *, unsigned char *, int)}
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from src/muxer/muxer_libav.c:22:
/usr/include/x86_64-linux-gnu/libavformat/avio.h:404:25: note: expected ‘int (*)(void *, const uint8_t *, int)’ {aka ‘int (*)(void *, const unsigned char *, int)’} but argument is of type ‘int (*)(void *, uint8_t *, int)’ {aka ‘int (*)(void *, unsigned char *, int)’}
  404 |                   int (*write_packet)(void *opaque, const uint8_t *buf, int buf_size),
      |                   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:722 : /home/valette/local/src/tvheadend-dmo-4.3~2336.g366e56290/build.linux/src/muxer/muxer_libav.o] Erreur 1
make[2] : on quitte le répertoire « /home/valette/local/src/tvheadend-dmo-4.3~2336.g366e56290 »
dh_auto_build: error: make -j1 V=1 returned exit code 2
make[1]: *** [debian/rules:35 : override_dh_auto_build] Erreur 2
make[1] : on quitte le répertoire « /home/valette/local/src/tvheadend-dmo-4.3~2336.g366e56290 »

### Reproduction

1) remove -6 for libav components in confifure and Makefile
2) Make -f debian/rules binary

and you get the failure

**Comment by Flole998** [comment]
You are using a modified version, issue reports for that are not accepted. Reproduce it without modifying the source/makefiles and update the reproduction steps if the issue still persists.

**Comment by EricV** [comment]
Nice nit picking. Problem is the same with the upstream git version if you look at 

https://github.com/tvheadend/tvheadend/blob/master/src/muxer/muxer_libav.c#L149

There is STILL not more channels field directly from avcontext... This change is documented in the ffmpeg 7.x API change. So no matter how you compile the code (provided you use ffmpeg 7.x code libraries and includes) and on what distribution it will not work with fffmpeg 7.

    c->channels      = ssc->es_channels;

**Comment by Flole998** [comment]
Ffmpeg 7.0 is not supported.

**Comment by EricV** [comment]
This is not a sustainable long term position in my opinion. So far, it ok but in 6 months...

**Comment by EricV** [comment]
Why closing. It brings infomrtaion.

**Comment by Flole998** [comment]
There is #1690 and any help with it is appreciated :)

It is not a bug, so it is not tracked as a bug.

**Comment by EricV** [comment]
Ok. But if it is not important for you, why should I care. I will fix my own version...

**Comment by Flole998** [comment]
Because that is how open source software works, I do not use Tvheadend with ffmpeg 7.x so I don't care and won't invest time into it. If you fix it a PR is appreciated and good practice.
