### ISSUE TITLE
[BUG]: 403 Error after re-installing TVH.

### ISSUE THREAD

**Issue by DeltaMikeCharlie** [tvheadend/tvheadend#1722]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2337~ge855f62e6~jammy_amd64

### Platform

Ubuntu 22.04 (Jammy)

### Architecture

Intel i686

### Category

Packaging

### Description

Installation vis DEB package, followed by removal and then re-installation results in 403 error.

Please see the forum posting for more details:

https://tvheadend.org/d/8687-login-always-results-in-403-forbidden/49

As a work-around, delete the user and groups created during the first installation before reinstalling.

### Reproduction

Install TVH from DEB.
Purge TVH.
Install TVH from DEB.
Browse to TVH.

**Comment by Leatherface75** [comment]
Still having this problem here.
Unable to login in webinterface but channels etc works in clients.
Sometimes it works but most of times not.
Those workarounds doesn't work either.
Seems to work better in Firefox but in Chrome based webbrowsers i get 403 error.
