### ISSUE TITLE
[FEATURE]: Add Time-Out to scan process

### ISSUE THREAD

**Issue by udippel** [tvheadend/tvheadend#1723]
### Description

Referring to https://tvheadend.org/d/8697-autoscan-badly-misses-time-out, I see this as a border case between bug and feature. 
Scanning muxes can result in endless loops that need to be aborted by the user. This is IMHHO 'buggy'. If a mux cannot be explored within a specific time frame, the scan process ought to abandon this max/channel and continue to the subsequent one. 

### Help and Guidance

I can offer any help necessary w.r.t. testing, and concepts. Though I can't contribute code.
I don't know if this is acceptable as proposal?

### Acceptance

- [X] The proposal will be developed and maintained by me

**Comment by Flole998** [comment]
I don't see any Tvheadend log in the forum? Also testing and concepts are not enough for a feature proposal, this is for active development only.
