### ISSUE TITLE
WebUI has no mechanism to show file name of completed recordings

### ISSUE THREAD

**Issue by snarkywolverine** [tvheadend/tvheadend#1726]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2199~g7b762336e

### Platform

Debian 12 (Bookworm)

### Architecture

Intel x86_64

### Category

WebGUI

### Description

As far as I can tell, there is no way to see the file name (or full path) of a recording in the Web UI.  I would expect it to be a selectable column in the "Finished Recordings" (or Failed Recordings) view, but do not see that option.

I watch shows by doing file conversions and using an experience external to TVHeadEnd; but without file names, it makes circling back to remove duplicated files more difficult.

**Comment by Flole998** [comment]
Not a bug.
