### ISSUE TITLE
[BUG]: Potential Issues with IPv6 URL Handling

### ISSUE THREAD

**Issue by sKyissKy** [tvheadend/tvheadend#1734]
### Tvheadend Version

v4.4 (stable)

### Build Number

4.4~d2e41b553e7cc6eb06fd21b42bbed4b3a1f28bc0

### Platform

openwrt (all)

### Architecture

ARMv8 (aarch64)

### Category

IPTV

### Description

Potential Issues with IPv6 URL Handling
The code provided does not explicitly show any handling for IPv6 addresses, which need to be enclosed in square brackets (e.g., [2001:db8::1]). This is crucial to differentiate the colons in the IPv6 address from the colon that separates the hostname and port number.

Enhancing IPv6 Support
To correctly handle IPv6 addresses, you need to modify the parsing logic to detect and process IPv6 addresses enclosed in square brackets. This can be done by checking if the host part of the URL starts with [ and ends with ].

### Reproduction

Here is an enhanced version of the urlparse function with added logic to handle IPv6 addresses:

#define uri_copy(y, x) \
  if (x.first) { \
    size_t len = x.afterLast - x.first; \
    if (x.first[0] == '[' && x.first[len - 1] == ']') { \
      /* Handle IPv6 address enclosed in brackets */ \
      y = strndup(x.first, len); \
    } else { \
      y = strndup(x.first, len); \
    } \
  }

int urlparse(const char *str, url_t *url) {
  UriParserStateA state;
  UriUriA uri;
  char *s, buf[256];

  if (str == NULL || url == NULL)
    return -1;

  urlreset(url);

  /* Parse */
  state.uri = &uri;
  if (uriParseUriA(&state, str) != URI_SUCCESS) {
    uriFreeUriMembersA(&uri);
    return -1;
  }

  /* Store raw */
  url->raw = strdup(str);

  /* Copy components */
  uri_copy(url->scheme, uri.scheme);
  uri_copy(url->host, uri.hostText);
  uri_copy(url->user, uri.userInfo);
  uri_copy(url->query, uri.query);
  uri_copy(url->frag, uri.fragment);

  uri_copy_static(buf, s, uri.portText);
  if (s) {
    url->port = atoi(s);
    free(s);
  } else if (*buf) {
    url->port = atoi(buf);
  } else {
    url->port = 0;
  }

  /* Handle path */
  UriPathSegmentA *path = uri.pathHead;
  while (path) {
    uri_copy_static(buf, s, path->text);
    if (url->path)
      url->path = realloc(url->path, strlen(url->path) + strlen(s ?: buf) + 2);
    else
      url->path = calloc(1, strlen(s ?: buf) + 2);
    strcat(url->path, "/");
    strcat(url->path, s ?: buf);
    path = path->next;
    free(s);
  }

  /* Split user/pass */
  if (url->user) {
    s = strstr(url->user, ":");
    if (s) {
      url->pass = strdup(s + 1);
      *s = 0;
    }
  }

  /* Cleanup */
  uriFreeUriMembersA(&uri);
  return 0;
}

Explanation
The uri_copy macro now includes a check for IPv6 addresses enclosed in square brackets.
This ensures that when the host part is an IPv6 address, it is correctly handled and copied.
With these changes, the urlparse function can correctly handle IPv6 URLs by ensuring the host part of the URL is appropriately processed when enclosed in square brackets. This should resolve issues related to parsing and handling IPv6 URLs in Tvheadend.

**Comment by Flole998** [comment]
Patches should be submitted as PRs.
