### ISSUE TITLE
[FEATURE]: Allow restricting UDP ports for IPTV reception (notably for RTSP)

### ISSUE THREAD

**Issue by Arno500** [tvheadend/tvheadend#1738]
### Description

I have a Freebox at home, in France, that allows to recast IPTV streams for all the channels that I have access to. This is great, but there is one issue: the streams are done via RTSP and only via UDP unicast. This means that if I want to containerize TVHeadend (which I do), I would either need to bind the whole container to the host (which I do not want to do, and it would conflict with other ports notably if I intend to use the HDHomerun emulator) or bind all UDP ports to the container (which is also a big no no) AND open all the ports in the software firewall that I have in place.

The other alternative would be to actually control the `client ports` that are sent through the initial SETUP request to only allow a specific range of ports to pass through. In the options, there would be an option for a minimum and a maximum port, with a pool available (since each connection takes a minimum of two ports) and as a user, you would be in charge to ensure there are enough ports for the number of input streams allowed in your various sources at all time. This is something that FFMPEG provides on their side and that can actually be really useful.

I already drafted a fix, this should be pretty trivial, but my time is limited for now, and I will be on holidays soon.

### Help and Guidance

I do not think I need particular help and guidance, but I simply want to ensure that I am going in the proper direction with the plan:
1. Add `Minimum UDP port` and `Maximum UDP port` in the options
2. When opening a stream, if the options above are set, take the lowest available port (+1 for the control channel) and lock them somewhere so they cannot be used until they are freed (or use the current logic of taking the current connection port as a base). I also need to make sure the two available ports are contiguous due to the protocol, but if my code is good, it should not be a problem.
3. If there are no more ports available, throw an error and clearly indicate to the user what is wrong

Would that fit the project as intended?

### Acceptance

- [X] The proposal will be developed and maintained by me

**Comment by Flole998** [comment]
> and lock them somewhere so they cannot be used until they are freed

This is the difficult part, as a port may be in use by another application. I have done something similar in a different project and IIRC you basically need to try to bind to 2 consecutive ports within the range, if it fails on the first one, move up 1 port, if it fails on the second one, move up 2 ports and try again, until it works out.

**Comment by Arno500** [comment]
Just pushed the first version of the feature here: #1751

**Comment by alo0** [comment]
Hello @Arno500 ,

First of all, thank you for your contribution.
I am in the same situation as you: would like to avoid host network for my TVH docker container and using Free ISP. 
Could you please explain me where your port settings are available in TVH ?

**Comment by Arno500** [comment]
Hello @alo0 ,
You should be able to find them in the general settings, with the "Expert" display mode only

**Comment by alo0** [comment]
Hi @Arno500 
Thanks. It works perfectly !

**Comment by SuNNjek** [comment]
Hi, sorry to respond to an old issue, but I was wondering if this also works for the integrated SAT>IP client.

I'm currently trying to set my tvheadend up to receive SAT>IP data, but I can't scan any muxes unless I completely disable my firewall which I would like to avoid ^^ I tried it with the min/max RTSP UDP ports settings but that also doesn't work.

**Comment by Arno500** [comment]
Hi, sorry for not answering earlier. Unfortunately no, I did not implement that for the other flows than IPTV reception. That said, it should be pretty trivial to implement, with the same idea from the IPTV side (basically allow the binding to fail without a catastrophic error, and `while` to try to find an available port specified in the config).
