### ISSUE TITLE
[BUG]:  Official install on Ubuntu 24.04 fails.

### ISSUE THREAD

**Issue by xxzandy** [tvheadend/tvheadend#1741]
### Tvheadend Version

v4.2 (unsupported)

### Build Number

4.3-2315~gab6ea89b1

### Platform

Other..

### Architecture

Intel x86_64

### Category

Configuration

### Description

tvheadebd not working and installing correctly on Ubuntu 24.04. Details below.

### Logfile

see below

### Reproduction

#################################the rest is more software related and less hardware#####################################
sudo ls
curl -1sLf 'https://dl.cloudsmith.io/public/tvheadend/tvheadend/setup.deb.sh' | sudo -E bash
sudo apt-get update
sudo apt install tvheadend
# choose a administrator for tvheadend: tvhadm44553-33333333
# pw: tvhadsdfdsm45433333
systemctl status tvheadend.service #ebabled and running
# 4151 /usr/bin/tvheadend -f -p /run/tvheadend.pid -u hts -g video
# (running under user hts)
# once again this was not created: /var/lib/tvheadend/.config
sudo reboot now
sudo su
cd 
## in the normal situation.

I also know (and am able) to build from the sources, but as this is a backend, so I want it to be updatable with standard tools.

**Comment by Flole998** [comment]
You're reporting an issue for some old version. Use latest version.
