### ISSUE TITLE
[BUG]: Playing a recording is ignoring stream profile (no transcoding)

### ISSUE THREAD

**Issue by ovaron76github** [tvheadend/tvheadend#1752]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2347~g1dc8ffe78

### Platform

Debian 12 (Bookworm)

### Architecture

Intel x86_64

### Category

Transcoding

### Description

When viewing recordings no transcoding is done. This is a little bit a problem if some one only has a low bandwith and is transcoding to lower bitrate but cannot see recordings. Recodings itself should be done in "original" format as others with bigger bandwith want to have better quality. In my oppinion recodings should be handled exactly like "live tv" in case of transcoding.

### Logfile

---

### Reproduction

Play a recrding and you see no transcoding is applied. Recodings are streamed as they are saved on hard drive.

**Comment by Flole998** [comment]
This is simply not supported as you are not streaming but downloading a recording.
