### ISSUE TITLE
[BUG]: HTSP Disconnect (broken pipe) - KODI HTSP client

### ISSUE THREAD

**Issue by LoneWolf-83** [tvheadend/tvheadend#1768]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2368~g55404da6c

### Platform

Other.. Ubuntu-24.04

### Architecture

Intel x86_64

### Category

HTSP

### Description

Hello,

I used tvheadend before and everything was working very well.
However, two weeks ago this issue started to appear.
I used to run tvheadend in a privileged proxmox lxc container - but because of this issue I decided to do a new installation of tvheadend on bare metal.
The new installation did not help. The same issue is happening.

I'm using two Hauppage WinTV USB DVB-C tuners with a Fujitsu Futro S740 running Ubuntu 24.04.

The problem is that the KODI HTSP connection gets disconnected.
This happens on WIFI and LAN with different devices.
I was thinking its a wifi issue - but as it happens on LAN as well this is not the case - also it used to work before without any issues.

I really like tvheadend and would like continue to use it.
But currently is un-usable. Timeshift is not working once the connection dopped.
When playing recordings the playback will stop and I have to press play again everytime this happens.
My wife and the kids really dont like the current situation.

I was searching for the issue the last weeks.
Did find many hints like this could be an EPG issues and so on.
I tried to disable any muxes I dont need and also disabling many services.
But nothing helped.

I also tried compiling tvheadend with and without transcoding support.

Any help would be appreciated.

### Logfile

https://pastebin.com/9it1RLGY

### Reproduction

1. start tvheadend
2. connect Kodi
3. play any TV channel or recording

**Comment by Flole998** [comment]
Kodi is disconnecting from Tvheadend before that according to your logs, there is nothing the server can do about it. Feel free to use wireshark to confirm that indeed Kodi is closing the connection and not Tvheadend.

**Comment by LoneWolf-83** [comment]
Ok, did that.
I captured two disconnects.
Here is a zip containing the pcap, kodi and tvheadend log.
https://drive.google.com/file/d/1Bzd5brWKgNBkLZ-2RIc6WTJ6NlIYo5-F/view?usp=drive_link

I'm not a wireshark expert, @Flole998 can you please help me to check if you are right?

**Comment by Flole998** [comment]
Kodi even logs the issue:
`2024-10-03 15:09:41.164 T:10449 warning <general>: AddOnLog: pvr.hts: demux read no data for at least 10 secs; restarting connection`
And in wireshark there are a lot of TCP retransmits for the data stream. So not a Tvheadend issue as Tvheadend is actually sending the data, it is just lost somewhere. (You might want to delete the pcap as it might contain passwords and other sensitive information).

**Comment by LoneWolf-83** [comment]
First of all: Thank you very much for your help!

I already deleted the file.

I saw that log message and I was thinking the server is not sending data.
Interesting. But still I have no idea how to solve the issue.
I did a router firmware upgrade to Fritz!OS 8 on my FritzBox7590 AX at the time when the issues started.
Propably I will do a downgrade for testing.
