### ISSUE TITLE
[BUG]: Quotation marks not escaped in API JSON

### ISSUE THREAD

**Issue by Flattermann78** [tvheadend/tvheadend#1770]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2370~g28de5c092

### Platform

Raspberry Pi OS (Bookworm)

### Architecture

ARMv8 (aarch64)

### Category

API

### Description

Calling http://tvheadend:9981/api/dvr/entry/grid_finished?start=0 creates invalid JSON structures (e.g. parse error: Invalid numeric literal at line 1, column 621) if the broadcaster included quotation marks in the program description (German issue I guess).

### Reproduction

1. record German TV with program descriptions containing quotation marks (")
2. Request the recording through the API 
3. Receive a non valid JSON as the "s are not escaped

**Comment by Flole998** [comment]
Can't reproduce, quotation marks in the "description" field of an entry on that page are escaped properly for me.

**Comment by Flattermann78** [comment]
You're right! I had a glitch with jr I missed while debugging.
