### ISSUE TITLE
[BUG]: max_rotor_move default of 120 is exceedingly long

### ISSUE THREAD

**Issue by ilikenwf** [tvheadend/tvheadend#1774]
### Tvheadend Version

v4.4 (stable)

### Build Number

All versions - NA

### Platform

Other..

### Architecture

Intel x86_64

### Category

Configuration

### Description

The default of 2 minutes before the rotor is made to move causes undue delays and made me think something was wrong with my DVB card. 

Even with just a 1 second delay my setup works, can we maybe consider a more sane default or at least make it clear to users using any configuration (is it advanced config only?) that enables this default value that they may need to reduce it if they notice it takes 2+ minutes for their system to lock and zap to whatever they want to watch?

See https://github.com/tvheadend/tvheadend/blob/master/src/input/mpegts/linuxdvb/linuxdvb_satconf.c#L706

**Comment by Flole998** [comment]
This is a sane default as the rotor position at startup is unknown and it might be all the way on the other side. Reducing it would cause issues with failed tunings for others. Your setup works with a 1 second delay if the rotor is close enough to it's target position, if its on the other end a 1 second delay would not be sufficient at all. As this is only a default value and it is only relevant for the startup, this is not a Bug. Feel free to add details or a warning about it to the documentation though: https://docs.tvheadend.org/documentation

**Comment by Flole998** [comment]
I just did a quick search and found plenty of rotors with 1.5°/second when used with 13V, which equals 120 seconds for 180°. The Selfsat HH-90 DiSEqC Motor is one of them. I am not sure why this was such a big issue for you, as it only affects the first tuning after a Tvheadend restart, so it shouldn't really be noticable during normal operations at all.

**Comment by ilikenwf** [comment]
@Flole998 my satellite has been parked at 99.2W for the PBS channels it has; even after a restart, I am forced to wait 2 minutes with the default value before a zap occurs, even though I'm already properly pointed at the satellite in question...so this could in fact be an order of operations issue?

**Comment by Flole998** [comment]
Tvheadend doesn't know the last position after a restart, that's why there are the 2 minutes delay. Once the position is known, the configured movement rate will be used, so that it doesn't take longer than it has to.

**Comment by ilikenwf** [comment]
Since we know what the desired service, mux, etc should look like why are we not checking before attempting to even move the rotor, if we can just lock it as is before trying to move?

**Comment by Flole998** [comment]
> Likewise, you seem to be implying that max_rotor_move is a minimum value for waiting, instead of a maximum - there's also a minimum but it has no default set so it may be a misused in the code, with the names flipped or something?

The "max_rotor_move" is the time the rotor needs for a full movement, from one end to the other, so the longest possible time the rotor could move. So at startup, this is the time that must pass to be sure, that the rotor reached its target position. All movements afterwards are calculated using the specified speed and the exact movement needed.

**Comment by ilikenwf** [comment]
I see... I guess it would be more beneficial for USALS systems than old school ones like mine, with the 10 foot C/Ku dish...my actuator is also very fast...

Even so it is unlikely that you have to move fully across the arc most of the time to be fair...

Having occasional polling and a pre-move check to see if we're already locked would be a neat feature, if I think of it maybe I'll get to it some year and pull request it.

**Comment by Flole998** [comment]
This is only ever used once after a Tvheadend restart. All subsequent moves will be calculated based on the specified rotation speed. So don't spend too much time on it, it'll only save 2 minutes after a restart for very few users (and as you've specified a significantly shorter value it won't really save you any time at all). Usually Tvheadend doesn't need to be restarted.

**Comment by ilikenwf** [comment]
Yeah, only if I'm bored...

I may at least try to mention it in the docs sometime if I get the chance.
