### ISSUE TITLE
[BUG]: TBS 6903X - Tunes Properly in tagged 4.2.8, same exact configuration in 4.3 (master) fails to tune - DVB-S

### ISSUE THREAD

**Issue by ilikenwf** [tvheadend/tvheadend#1777]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3.r2374

### Platform

Other..

### Architecture

Intel x86_64

### Category

DVB

### Description

4.2.8 is able to properly utilize my DVB card and execute diseqc commands, and tune. Under the current master, **which is tens of thousands of commits ahead**, it is not even executing diseqc commands as my positioner does not "click" as if it is moving.

I have no idea what could possibly cause this and have even attempted to restart the networks/muxes/services from scratch but am unable to even scan, execute diseqc commands, or get a lock under 4.3/master.

I am using kernel 6.10.10 with @deeptho version of the drivers.

I would share logs from the success of 4.2.8 but there is no point - it subscribes and works perfectly without any trouble so see the 4.3 logs below...

### Logfile

Oct 17 07:16:29 settop tvheadend[70768]: mpegts: 12095H in 99.2W - tuning on TurboSight TBS 6903x  #0 : DVB-S #0
Oct 17 07:16:29 settop tvheadend[70768]: subscription: 000F: "127.0.0.1 [ settop | Kodi Media Center ]" subscribing on channel "99.2W/12095H/{PMT:1000}", weight: 150, adapter: "Turbo>
Oct 17 07:16:41 settop tvheadend[70768]: subscription: 000F: service instance is bad, reason: No input detected
Oct 17 07:16:43 settop tvheadend[70768]: subscription: 000F: No input source available for subscription "127.0.0.1 [ settop | Kodi Media Center ]" to channel "99.2W/12095H/{PMT:1000}"
Oct 17 07:16:45 settop tvheadend[70768]: subscription: 000F: No input source available for subscription "127.0.0.1 [ settop | Kodi Media Center ]" to channel "99.2W/12095H/{PMT:1000}"
Oct 17 07:16:47 settop tvheadend[70768]: subscription: 000F: No input source available for subscription "127.0.0.1 [ settop | Kodi Media Center ]" to channel "99.2W/12095H/{PMT:1000}"

**Comment by ilikenwf** [comment]
The build commands utilized can be seen in the Arch PKGBUILDs for each version:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tvheadend-git

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tvheadend

**Comment by ilikenwf** [comment]
In addition, for the TBS module config, I have the following in case this has anything to do with it:

`options stid135 nostat mis=1 ts_nosync=0`

**Comment by Flole998** [comment]
The version number you stated is not an official/unmodified version number. Please copy it exactly as it appears on the about page or when running with the paramter to show the version number on startup.

Also this issue is missing debug logs (from the dvb subsystem).

**Comment by deeptho** [comment]
For what it is worth:
4.3^20240111gitc9b38a8-5.fc40 (from the about screen)
works fine with these drivers and with tbs6909x which is a very similar card.

**Comment by ilikenwf** [comment]
I'll...keep banging my head against it once I get a chance. Seems that prior to me most DVB people stopped maintaining their packages under my distro, Archlinux.
