### ISSUE TITLE
[BUG]: Login Credentials

### ISSUE THREAD

**Issue by vengatesh-alagarsamy-infosys** [tvheadend/tvheadend#1779]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2374~g26ec161fb

### Platform

Ubuntu 20.04 (Focal)

### Architecture

ARMv6 (arm)

### Category

API

### Description

After install im trying to open http://localhost:9981 
its asking username and password.
What is default username and password

**Comment by Flole998** [comment]
This is the bug tracker, questions like this should go into the [forum](https://tvheadend.org).
