### ISSUE TITLE
[BUG]: cannot save timeshift setting

### ISSUE THREAD

**Issue by alexhass** [tvheadend/tvheadend#1782]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2180

### Platform

Debian 11 (Bullseye)

### Architecture

Intel x86_64

### Category

API

### Description

I canno save the timeshift settings in libreelec 12.0.1 withtvheadend 4.3

### Logfile

Not avsilable

### Reproduction

Enable, save, form is broken

**Comment by Flole998** [comment]
This issue is missing debug logs, also a trace of the http requests sent is needed.

**Comment by alexhass** [comment]
Check save to ram, save. Checkbox is disabled.

**Comment by alexhass** [comment]
Flo i guess you need to repro to fix, so repro first and you do not need any logs anymore.

**Comment by dave-p** [comment]
On my home Tvheadend installation (4.3.2366) the timeshift configuration controls in the UI work as expected. On a LibreElec installation (12.0.0.1 on RPi4 with the stock Tvheadend 4.3.2180) the timeshift configuration does not work, and there are a large number of errors on the browser console when that screen is displayed.

It seems that this is a LibreElec problem.

**Comment by Flole998** [comment]
Also an old version is used.

**Comment by CvH** [comment]
thats an very old bug that exist since the adding of these timeshift to ram, I opened a issue 9years ago but was never fixed
there was some workaround to enable the setting but I cant really remember how I managed it

the following problem exist crossplatform at the least till 4.3-2374~g26ec161fb (capture is from ubuntu 24.04)
![timeshift](https://github.com/user-attachments/assets/d89da855-96c7-43b6-a1ef-986725dcb6de)

**Comment by dave-p** [comment]
That will be [https://old.tvheadend.org/issues/4487](https://old.tvheadend.org/issues/4487)

"To workaround:
User interface level: expert
Persistent user interface level: yes"

On my LibreElec setup, User Interface level for the "*" user was set to "default", and the Default View level was "Advanced". Persistent View Level was "on". Changing Default View Level to "expert" fixed it.

@Flole998 should this issue be re-opened to provide visibility of this known bug?

**Comment by Flole998** [comment]
Once the necessary logs are added it can be reopened. If there are errors in the browser console, those should also be provided

**Comment by dave-p** [comment]
This is the error reported in the browser console (Brave):

```
Uncaught TypeError: Cannot read properties of null (reading 'getValue')
    at Object.onchange (tvh.js.gz:900:631)
    at S.fonchange (tvh.js.gz:837:6)
    at h.Event.fire (tvh.js.gz:1:33638)
    at S.fireEvent (tvh.js.gz:1:30627)
    at S.setValue (tvh.js.gz:338:6)
    at S.onRender (tvh.js.gz:1:597601)
    at S.onRender (tvh.js.gz:332:292)
    at S.render (tvh.js.gz:1:165343)
    at S.renderItem (tvh.js.gz:1:223215)
    at S.renderAll (tvh.js.gz:1:198512)
```

The javascript is trying to read the status of the "Unlimited time" and "Unlimited size" boxes from the form, but those boxes don't exist in Advanced view mode. I'll run some more tests and raise a PR if I can fix the issue.

**Comment by alexhass** [comment]
Thanks guys! 

Hopefully, libreelec can release a new build based on latest code. I also have strange flickering issues when changing tv channels and like to know if this defect is also fixed in latest code.
