### ISSUE TITLE
[BUG]: mux does not pick up a name from m3u iptv list when pipe:// instead of http:// is used

### ISSUE THREAD

**Issue by glenb77** [tvheadend/tvheadend#1784]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2366~g9ac57a0c1

### Platform

Other..

### Architecture

Intel x86_64

### Category

IPTV

### Description

In an m3u local file as source for an automatic network, when i have an entry that specifies pipe:// after the list is processed the mux only has the url name and not a name from tvg-id. the tvg-id is unchanged from the original only the line that passes the url link is changed from provider's link. when the https:// link is in the m3u playlist the name gets picked up correctly.

### Reproduction

list with pipe, example entry:
#EXTINF:-1 tvg-id="ABC.(WABC).New.York,.NY.us" tvg-name="WABC (New York) ABC East" tvg-logo="http://schedulesdirect-api20141201-logos.s>
pipe:///etc/tvheadend/frtvff hls/WABCDT1

result mux no tvg-name or id

if provider http is in it, mux name is correct

**Comment by Flole998** [comment]
At the time the issue report was filed that version was already outdated. Reproduce with latest master and report again if the bug still exists. Also a log file showing the issue is required.
