### ISSUE TITLE
[BUG]: play channel in external program - download has no file extension

### ISSUE THREAD

**Issue by M95D** [tvheadend/tvheadend#1788]
### Tvheadend Version

v4.4 (stable)

### Build Number

adef81b8d2a6edb3a665679f394bac05b7dc91c8

### Platform

Other..

### Architecture

ARMv7 (arm)

### Category

WebGUI

### Description

I'm using tvheadend on OpenWrt. The current package is built from git commit adef81b8d2a6edb3a665679f394bac05b7dc91c8 from 2024-08-12. The build does not include transcoding.

1) Open tvheadend EPG page in Firefox. (The bug possibly affects other browsers too, but I only have FF installed.)
2) Open details page of a currently running program by clicking the icon in the Details column.
3) Click the Play button on the bottom of the popup window.
4) A dowload starts. The file is a .m3u playlist, but the proposed file name is a random string without extension and the mimetype is "application/vnd.apple.mpegurl".
I consider both wrong.
- A file without extension can't be associated with a program and most (all?) windows players use file extension to determine file type, so automatic download and play with external program doesn't work and can't work no matter how the file associations are set up. The filename should be the program name or channel name and the extension should be ".m3u".
- "application/vnd.apple.mpegurl" is an Apple abuse of standards. It should be "audio/mpegurl" instead.

Thank you.

**Comment by Flole998** [comment]
Can't reproduce, the full version number should be stated and no 4.4 version has been released yet.

**Comment by M95D** [comment]
If the build is from a git commit, then there is no version number, and this page forces a choice in that selection box.

**Comment by Flole998** [comment]
There is always a version number, check the "about" page or check the logs at startup.

**Comment by M95D** [comment]
It is a clean unmodified build, except for a [tiny patch](https://github.com/openwrt/packages/blob/master/multimedia/tvheadend/patches/050-iconv-test-continue.patch) that bypasses an iconv test.

Well, I can't find the version. Maybe you can.
[tvheadend.log](https://github.com/user-attachments/files/18051744/tvheadend.log)

![TVH-version](https://github.com/user-attachments/assets/4e7ef0d6-01a4-4de1-b118-0030a2956703)

**Comment by Flole998** [comment]
That patch is known to cause problems and there have clearly been other modifications as the version number is not shown. Contact the maintainer of whatever you have installed there for support.

**Comment by M95D** [comment]
I'm the maintainer. Without the patch it won't start, so it won't be possible to reproduce anything.
And why do you insist on a version? A git commit is obviously the most precise determination of what source code was used to build it.

**Comment by M95D** [comment]
This is the openwrt makefile for tvheadend package:
https://github.com/openwrt/packages/blob/master/multimedia/tvheadend/Makefile
As you can see there are no other modifications.

**Comment by Flole998** [comment]
It won't start cause you don't satisfy the requirements. Fix that and it will start. Official, unmodified builds against official (non-stub) iconv versions work perfectly fine.

**Comment by M95D** [comment]
Can we get back to this issue and not discuss OpenWrt platform decisions? Or are you saying that missing iconv generates random filenames without extension?

![FF-TVH-play](https://github.com/user-attachments/assets/7122d0d3-6bed-4023-a255-d42f8893a43d)
