### ISSUE TITLE
[BUG]: play from webui in external program: download has no file extension

### ISSUE THREAD

**Issue by M95D** [tvheadend/tvheadend#1789]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2375~g653bd0400

### Platform

Other..

### Architecture

ARMv7 (arm)

### Category

WebGUI

### Description

Tvheadend built from untouched git master branch, running on Gentoo Linux armv7h.
Firefox version used is 133.0.3 (64-bit) running on Windows 10.

On Firefox, when trying to play a channel or a recording from WebUI, a download starts. The file is a .m3u playlist, but the proposed file name is a random string without extension and the mimetype is "application/vnd.apple.mpegurl".

![tvheadend-ff-download](https://github.com/user-attachments/assets/6f796b0d-2fb0-4b7e-9367-db374212b045)

**Bug 1:**
A file without extension can't be associated with a program and most (all?) windows players use file extension to determine file type, so automatic download and play with external program doesn't work and can't work no matter how the file associations are set up. The filename should be the program name or channel name and the extension should be ".m3u".

This bug is Firefox-specific. Chrome-base browsers probably add extension automatically based on mimetype. I don't have Apple browser to test.

**Bug 2:**
"application/vnd.apple.mpegurl" is an Apple abuse of standards. It should be "audio/mpegurl" instead.

Thank you.

### Logfile

```
Configure arguments:
  --disable-cardclient --disable-cwc --disable-cccam --disable-capmt --disable-constcw --disable-satip_server --disable-satip_client --disable-hdhomerun_server --disable-hdhomerun_client --disable-iptv --disable-timeshift --disable-avahi --disable-zlib --disable-pcre --disable-uriparser --disable-ccache --disable-tvhcsa --disable-dbus_1 --disable-pcloud_cache --disable-ddci --disable-libav --disable-ffmpeg_static --disable-libx264 --disable-libx264_static --disable-libx265 --disable-libx265_static --disable-libvpx --disable-libvpx_static --disable-libtheora --disable-libtheora_static --disable-libvorbis --disable-libvorbis_static --disable-libfdkaac --disable-libfdkaac_static --disable-libopus --disable-libopus_static

Compiler:
  Using C compiler:                        cc
  Build for arch:                          armv7a

Binaries:
  Using PYTHON:                            python
  Using GZIP:                              gzip
  Using BZIP2:                             bzip2

Options:
  pie                                      yes
  ccdebug                                  no
  cardclient                               no
  cwc                                      no
  cccam                                    no
  capmt                                    no
  constcw                                  no
  linuxdvb                                 yes
  satip_server                             no
  satip_client                             no
  hdhomerun_client                         yes
  hdhomerun_server                         no
  hdhomerun_static                         yes
  iptv                                     no
  tsfile                                   yes
  dvbscan                                  yes
  timeshift                                no
  trace                                    yes
  avahi                                    no
  zlib                                     no
  libav                                    no
  ffmpeg_static                            no
  libx264                                  no
  libx264_static                           no
  libx265                                  no
  libx265_static                           no
  libvpx                                   no
  libvpx_static                            no
  libtheora                                no
  libtheora_static                         no
  libvorbis                                no
  libvorbis_static                         no
  libfdkaac                                no
  libfdkaac_static                         no
  libopus                                  no
  libopus_static                           no
  nvenc                                    no
  vaapi                                    no
  mmal                                     no
  omx                                      no
  inotify                                  yes
  epoll                                    yes
  pcre                                     no
  pcre2                                    yes
  uriparser                                no
  ccache                                   no
  tvhcsa                                   no
  bundle                                   no
  pngquant                                 no
  kqueue                                   no
  dbus_1                                   no
  android                                  no
  gtimer_check                             no
  slow_memoryinfo                          no
  libsystemd_daemon                        no
  pcloud_cache                             no
  ddci                                     no
  cclang_threadsan                         no
  gperftools                               no
  execinfo                                 yes
  W_unused_result                          yes
  f_stack_protector                        yes
  f_stack_protector_strong                 yes
  f_stack_check                            yes
  f_PIE                                    yes
  strlcat                                  yes
  strlcpy                                  yes
  fdatasync                                yes
  getloadavg                               yes
  atomic32                                 yes
  atomic64                                 yes
  atomic_time_t                            yes
  atomic_ptr                               yes
  bitops64                                 yes
  lockowner                                yes
  qsort_r                                  yes
  time_lld                                 yes
  gmtoff                                   yes
  recvmmsg                                 yes
  sendmmsg                                 yes
  ifnames                                  yes
  py_gzip                                  yes
  bin_pkg_config                           yes
  bin_xgettext                             yes
  bin_msgmerge                             yes
  bin_gzip                                 yes
  bin_bzip2                                yes
  ssl                                      yes
  linuxdvbapi                              yes
  linuxdvb_ca                              yes
  inotify_h                                yes
  inotify_init1                            yes
  epoll_create1                            yes
  mpegts                                   yes
  mpegts_dvb                               yes

Packages:
  openssl                                  3.3.2
  libpcre2-8                               10.44

Installation paths:
  Prefix:                                  /usr/local
  Binaries:                                ${prefix}/bin
  Libraries:                               ${prefix}/lib
  Data files:                              ${prefix}/share
  Man pages:                               ${datadir}/man
```
Log file (Irrelevant, but I'm sure someone will ask.)
```
# /usr/local/bin/tvheadend -C -B --nosyslog
2024-12-11 08:43:12.157 [   INFO] main: Log started
2024-12-11 08:43:12.158 [   INFO] config: Using configuration from '/usr/bin/.config/hts'
2024-12-11 08:43:12.158 [   INFO] http: Starting HTTP server 0.0.0.0:9981
2024-12-11 08:43:12.159 [   INFO] htsp: Starting HTSP server 0.0.0.0:9982
2024-12-11 08:43:12.167 [   INFO] config: loaded
2024-12-11 08:43:12.167 [   INFO] config: scanfile (re)initialization with path <none>
2024-12-11 08:43:12.170 [   INFO] descrambler: adding CAID 2600/FFFF as ConstCW interval 10000ms pc 20 ep default (BISS)
2024-12-11 08:43:12.170 [   INFO] descrambler: adding CAID 0E00/FFFF as MultiPID interval 1000ms pc 2 ep default (PowerVu)
2024-12-11 08:43:12.198 [   INFO] linuxdvb: adapter added /dev/dvb/adapter0
2024-12-11 08:43:12.213 [   INFO] dvr: Creating new configuration ''
2024-12-11 08:43:12.214 [   INFO] epggrab: module uk_freesat created
2024-12-11 08:43:12.214 [   INFO] epggrab: module uk_freesat_eit created
2024-12-11 08:43:12.214 [   INFO] epggrab: module uk_freeview created
2024-12-11 08:43:12.214 [   INFO] epggrab: module nz_freeview2 created
2024-12-11 08:43:12.214 [   INFO] epggrab: module nz_freeview1 created
2024-12-11 08:43:12.214 [   INFO] epggrab: module viasat_baltic created
2024-12-11 08:43:12.214 [   INFO] epggrab: module Bulsatcom_39E created
2024-12-11 08:43:12.214 [   INFO] epggrab: module uk_cable_virgin created
2024-12-11 08:43:12.214 [   INFO] epggrab: module eit created
2024-12-11 08:43:12.214 [   INFO] epggrab: module psip created
2024-12-11 08:43:12.223 [   INFO] epggrab: module opentv-ausat created
2024-12-11 08:43:12.223 [   INFO] epggrab: module opentv-skyit created
2024-12-11 08:43:12.225 [   INFO] epggrab: module opentv-skynz created
2024-12-11 08:43:12.225 [   INFO] epggrab: module opentv-skyuk created
2024-12-11 08:43:12.226 [   INFO] epggrab: module xmltv created
2024-12-11 08:43:12.233 [   INFO] tbl-eit: module eit - scraper disabled by config
2024-12-11 08:43:12.233 [   INFO] epgdb: parsing 1685685 bytes
2024-12-11 08:43:12.339 [   INFO] epgdb: loaded v3
2024-12-11 08:43:12.339 [   INFO] epgdb:   config     1
2024-12-11 08:43:12.339 [   INFO] epgdb:   broadcasts 7467
2024-12-11 08:43:12.340 [   INFO] dvr: Purging obsolete autorec entries for current schedule
2024-12-11 08:43:12.345 [ NOTICE] START: HTS Tvheadend version 4.3-2375~g653bd0400 started, running as PID:21080 UID:2 GID:1000, CWD:/build/tvheadend CNF:/usr/bin/.config/hts
2024-12-11 08:43:12.912 [   INFO] scanfile: DVB-S - loaded 1 regions with 116 networks
2024-12-11 08:43:12.912 [   INFO] scanfile: DVB-T - loaded 46 regions with 1134 networks
2024-12-11 08:43:12.912 [   INFO] scanfile: DVB-C - loaded 20 regions with 82 networks
2024-12-11 08:43:12.912 [   INFO] scanfile: ATSC-T - loaded 2 regions with 13 networks
2024-12-11 08:43:12.912 [   INFO] scanfile: ATSC-C - loaded 1 regions with 5 networks
2024-12-11 08:43:12.912 [   INFO] scanfile: ISDB-T - loaded 2 regions with 1297 networks
2024-12-11 08:43:22.167 [   INFO] mpegts: 370MHz in RDS - tuning on Si2168 DVB-C
2024-12-11 08:43:22.175 [   INFO] subscription: 0001: "scan" subscribing to mux "370MHz", weight: 5, adapter: "Si2168 DVB-C", network: "RDS", service: "Raw PID Subscription"
2024-12-11 08:43:25.817 [   INFO] mpegts: 370MHz in RDS scan complete
2024-12-11 08:43:25.817 [   INFO] subscription: 0001: "scan" unsubscribing
[...]
```

### Reproduction

- Open tvheadend EPG page in Firefox.
- Open details page of a currently running program by clicking the icon in the Details column.
- Click the Play button on the bottom of the popup window.
- A dowload starts.

Alternatively:
- Open tvheadend Finished Recordings page in Firefox.
- Click Play on a recording.

**Comment by dave-p** [comment]
I believe this is an issue with the browser and operating system.

I don't use Windows but I've tried the same version of Firefox running on KDE under Linux. On my system the browser downloads a playlist with the extension 'm3u8' which it then opens with VLC to play the channel.

In the Tvheadend source code, playlists are sent with the Mime type "audio/x-mpegurl". From experiments with KDE, it is the desktop which associates a Mime type with a file extension, then the browser determines what to do with the file from its Applications list in Settings - in my case it opens all Media playlists with VLC.

Presumably Windows has a similar way of translating a Mime type into a file extension?

**Comment by M95D** [comment]
> I believe this is an issue with the browser and operating system.
> 
> I don't use Windows but I've tried the same version of Firefox running on KDE under Linux. On my system the browser downloads a playlist with the extension 'm3u8' which it then opens with VLC to play the channel.
> 
> In the Tvheadend source code, playlists are sent with the Mime type "audio/x-mpegurl". From experiments with KDE, it is the desktop which associates a Mime type with a file extension, then the browser determines what to do with the file from its Applications list in Settings - in my case it opens all Media playlists with VLC.
> 
> Presumably Windows has a similar way of translating a Mime type into a file extension?

As I said in the bug report, in Windows, mimetypes aren't a thing. Programs determine filetypes by extension only.

And there is no such thing as converting a mimetype into a file extension. That would be unreliable/inconsistent, as one mimetype can map to many extensions. If Linux converts mimetypes to file extensions, then it's a mistake. File associations in Linux were a complete mess since the beginning.
I did a test with Windows Edge brosers and that one downloads a .m3u file, not .m3u8. In fact the mimetype doesn't specify if the playlist is encoded UTF-8 or not, so you see, that generates ambiguity.

Speaking of inconsistent behaviour, at least "application/vnd.apple.mpegurl" and the vendor-independent "audio/mpegurl" are written in [the standard](https://www.rfc-editor.org/rfc/rfc8216.html) (page 9). The mimetype you have "audio/x-mpegurl" is not.

**Comment by M95D** [comment]
> I believe this is an issue with the browser and operating system.
> 
> I don't use Windows but I've tried the same version of Firefox running on KDE under Linux. On my system the browser downloads a playlist with the extension 'm3u8' which it then opens with VLC to play the channel.
> 
> In the Tvheadend source code, playlists are sent with the Mime type "audio/x-mpegurl". From experiments with KDE, it is the desktop which associates a Mime type with a file extension, then the browser determines what to do with the file from its Applications list in Settings - in my case it opens all Media playlists with VLC.
> 
> Presumably Windows has a similar way of translating a Mime type into a file extension?

As I said in the bug report, in Windows, mimetypes aren't a thing. Programs determine filetypes by extension only.

And there is no such thing as converting a mimetype into a file extension. That would be unreliable/inconsistent, as one mimetype can map to many extensions. If Linux converts mimetypes to file extensions, then it's a mistake. File associations in Linux were a complete mess since the beginning.
I did a test with Windows Edge brosers and that one downloads a .m3u file, not .m3u8. In fact the mimetype doesn't specify if the playlist is encoded UTF-8 or not, so you see, that generates ambiguity.

Speaking of inconsistent behaviour, at least "application/vnd.apple.mpegurl" and the vendor-independent "audio/mpegurl" are written in [the standard](https://www.rfc-editor.org/rfc/rfc8216.html) (page 9). The mimetype you specified (audio/x-mpegurl) is not.

**Comment by dave-p** [comment]
This is an edited output from tcpdump on the client machine when playing a channel from the Tcheadend EPG UI. First the request:
```
GET /play/ticket/stream/channel/f6b6b22136bac78be6363ea3e0923cc3?title=This%20Morning HTTP/1.1
Host: x.x.x.x:9981
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en
Accept-Encoding: gzip, deflate
Referer: http://x.x.x.x:9981/extjs.html
DNT: 1
Connection: keep-alive
Cookie: ...
Upgrade-Insecure-Requests: 1
Priority: u=0, i
```
Then the reply:
```
HTTP/1.1 200 OK
Server: HTS/tvheadend
Cache-Control: no-cache
Connection: Keep-Alive
Content-Type: audio/x-mpegurl
Content-Length: 155

#EXTM3U
#EXTINF:-1,This Morning
http://x.x.x.x:9981/stream/channel/f6b6b22136bac78be6363ea3e0923cc3?ticket=86b73aa901f22082d79e64b2be1d2c31b8b2ce26
```
No filename is exchanged, only the mimetype.

**Comment by Flole998** [comment]
Firefox on Windows doesn't add a file extension, Chrome does. However, a bug that is specific to a single browser on a single OS is a bug in the browser IMO. If the same browser works on a different platform, that underlines this assumption. If Firefox won't fix it after opening a bug report there we might have to work around it, but that will likely be a breaking change for the API.

I don't know why Firefox on Windows messes around with the Mime-Type, but that's certainly not a Tvheadend issue and some Firefox-Dev should look into that. The current mime-type Tvheadend uses has been used since the beginning without any issues, and also other software uses it. Changing it could cause issues.

@chewitt is a Mac User, I'm wondering how it behaves on Chrome, Safari and Firefox on Mac? If you find some spare time, could you test it please?

**Comment by chewitt** [comment]
@Flole998 Firefox and Chrome download the `.m3u` file. Safari spawns a new tab and plays video.

**Comment by M95D** [comment]
Have a look at `GET /play/ticket/stream/channel/f6b6b22136bac78be6363ea3e0923cc3?title=This%20Morning HTTP/1.1`
Why can't you replace `f6b6b22136bac78be6363ea3e0923cc3` with `channel_name.m3u`? I'm sure tvheadend clients will require minimal modifications (if they do any string checking at all, which I doubt).

**Comment by Flole998** [comment]
Because then the channel ID would be gone and Tvheadend would have no way to know which channel you want to play.

**Comment by M95D** [comment]
`f6b6b22136bac78be6363ea3e0923cc3.m3u` then?

**Comment by Flole998** [comment]
And that's where the breaking API change would be. Currently it is sufficient to specify the channel ID, with that change it would be required to specify the m3u suffix for it. And the only reason is Firefox on Windows working differently than on Linux/Mac and all other Browsers on all platforms. Looks like a bug in Firefox to me, also that it's showing the wrong mime type.

**Comment by M95D** [comment]
1. Channel ID comes from tvheadend. Clients, unless they do string/input checking, will accept anything tvheadend sends to them. Yes, it's a hack, I know. Continue to 2.
2. Why does it have to be one or the other? Accept both on the server. Change the UI to send `channel_id.m3u` and allow the other clients to send it without extension.

**Comment by M95D** [comment]
I'm unable to formulate a bug report for it. What would I say? "I requested a file without extension from a site and the download doesn't have a file extension?"

**Comment by Flole998** [comment]
You requested a file which has Mime-Type `audio/x-mpegurl` and Firefox incorrectly shows it as `something different`. Additionally on Linux and Mac Firefox automatically adds a file extension to it, as all other tested browsers on all platforms do, just Firefox on Windows is not doing it. That is at least unexpected and probably unintended.

**Comment by M95D** [comment]
And they would reply: "Not a bug. `audio/x-mpegurl` doesn't exist. We corrected it to the closest existing mimetype we found."

**Comment by M95D** [comment]
OK, let's end this. It's clear you're not interested in respecting any standards or otherwise fixing this bug.

**Comment by Flole998** [comment]
Btw: The bug was already reported to Firefox 3 years ago but then things stalled: https://bugzilla.mozilla.org/show_bug.cgi?id=1735014. They confirmed it is a regression on their end that the mimetype is incorrectly shown as the apple one. The screenshots also indicate that the file extension was auto-added in FF 92, and not anymore in FF 93. So this is in fact not our bug and firefox already acknowledged this regression.
