### ISSUE TITLE
[BUG]: Manually created recordings fail while recordings from EPG work well

### ISSUE THREAD

**Issue by raspby4** [tvheadend/tvheadend#1791]
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2155~gfe4df311d

### Platform

Raspberry Pi OS (Bookworm)

### Architecture

ARMv8 (aarch64)

### Category

PVR/DVR

### Description

If I initiate a recording either
- as a scheduled recording from EPG of the tvheadend web interface
- by creating an autorec
- by just starting a recording of a running live TV stream in kodi
then the recording is saved as expected in a file at the specified path.

However, if I add a new recording in the tvheadend web interface unter "upcoming / current recordings" manually, then nothing is being recorded. In the recording folder a file of 1 KB in size is being created and the interface shows the error "time missed". I also observed the error "file missing".

Taking a closer look at the timer files in .config/hts/dvr/log there is a difference in the EPG and manual created timers: While EPG timers have entries for the parameters "dvb_eid" and "broadcast" these parameters are 0 for the manual timers.

If I create a timer from EPG and then edit the start and stop time manually the recording works fine.

### Logfile

Relevant output of "journalctl -u tvheadend" seems to be these lines:
Dez 16 10:59:14 raspberrypi systemd[1]: tvheadend.service: Main process exited, code=killed, status=11/SEGV
Dez 16 10:59:14 raspberrypi systemd[1]: tvheadend.service: Failed with result 'signal'

### Reproduction

Starting tvheadend service as user "pi" and group "video".
Create a recording timer manually in the web interface.

**Comment by Flole998** [comment]
This issue report is missing debug logs.

**Comment by DeltaMikeCharlie** [comment]
@raspby4 - I can recreate this if the dates are in the past.  Have you confirmed that your dates are in the future?

**Comment by Flole998** [comment]
https://docs.tvheadend.org/documentation/appendices/debugging

**Comment by raspby4** [comment]
Ok, I read the page on debugging, but I guess I need some help which kind of log is usefull to you in this case...

For my understanding (from a perspective of a basic to medium experienced Debian user - far far away from expert level) it sounds that there are several kinds of logs:

1. The standard tvheadend log output to file or syslog. This can be used with the --trace option for several modules. Which modules would be relevant for this kind of bug? Example: tvheadend -u hts -g video --trace <modules>

2. A dgb version. Seems to be another version specialized for debugging. However, no examples are given how to start this up ("tvheadend-dgb ..."). Or is this package just an amendment to the regular tvheadend to enable --debug and --trace option?

3. Finally the gdb tool is mentioned for crash reports. As my syslog states "main process exited, code=killed" you probably need that one as well?

**Comment by Flole998** [comment]
You are experiencing a crash. That means you definitely need the debug version (it will basically just "add" the debug stuff, no need to modify anything, just install it alongside the other version). No need to trace at this point, you just need to figure out where tvheadend logs to and then find the crash report (see in the docs how it should look like).

**Comment by raspby4** [comment]
As per your request here comes the gdb log:
[gdb_log.txt](https://github.com/user-attachments/files/18177963/gdb_log.txt)

In order to create the log I stopped the tvheadend service, then started tvheadend with gdb --args, created a new timer and finally waited until the start of the recording time (the same time the web interface became unreachable).

**Comment by Flole998** [comment]
You still have to grab a stacktrace using the `bt` command when gdb catches the signal. Or not use gdb at all but simply look at the log file after a crash.

**Comment by raspby4** [comment]
Ok, here another try with backtrace. What I did to create this log:
1. sudo gdb --args tvheadend -u pi -g video
2. "run" command
3. Pause with ^C and create a backtrace with "bt full" before crash
4. "continue" command
5. Let TVH crash wile attempting to record a manually scheduled timer
6. Create another backtrace with "bt full" after crash

[gdb_log.txt](https://github.com/user-attachments/files/18247457/gdb_log.txt)

Merry X-mas :)

**Comment by Flole998** [comment]
Your build is missing debug symbols. Also no point to grab a stacktrace at a random point during execution, the only relevant one at this point is after the crash

**Comment by raspby4** [comment]
Alright, one more try. Probably I have just checked apt-cache for tvheadend-dbg package instead of looking for actually installed packages. Anyway, hope we are getting closer...

[gdb_log.txt](https://github.com/user-attachments/files/18264209/gdb_log.txt)

**Comment by Flole998** [comment]
This is exactly the reason why I refuse to accept reports for older versions. This has been fixed 10 months ago. No more exceptions, only bug reports for latest master are accepted from now on.

**Comment by raspby4** [comment]
Well, from a certain perspective this is good news anyway, because it means that this bug has already been fixed - though I understand your resentment about spending time on such a case. According to the TVH download section the version 4.3-2375~g653bd0400~raspbianbookworm seems to be the latest master. As this is not yet available in the standard raspberry apt package repo I obviously have the options to either wait or add the TVH repository. Any suggestions how I can contact and support those guys who maintain the official raspberry repo?

Thanks for your help so far!
